"""
This type stub file was generated by pyright.
"""

import types
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Any, TYPE_CHECKING
from collections.abc import Generator
from typing_extensions import Self
from .bytecode_transformation import Instruction

"""
Bytecode debugger for Dynamo-optimized code.

This module provides a pdb-like debugger for stepping through Python bytecode
one instruction at a time, with the ability to inspect the value stack,
locals, and globals.

Usage:
    >>> # xdoctest: +SKIP
    >>> import torch
    >>>
    >>> @torch.compile
    >>> def my_fn(x):
    ...     return x + 1
    >>>
    >>> with torch._dynamo.bytecode_debugger.debug():
    ...     my_fn(torch.randn(3))  # Debugger activates on Dynamo-generated code

Programmatic breakpoints (for Dynamo developers):
    In PyCodegen, use create_breakpoint() to insert a debugger stop:

        from torch._dynamo.bytecode_transformation import create_breakpoint
        codegen.extend_output(create_breakpoint())
"""
if TYPE_CHECKING:
    ...
_HAS_SYS_MONITORING = ...
class _BreakpointMarker:
    """Sentinel constant that signals the debugger to break.

    Usage in PyCodegen:
        from torch._dynamo.bytecode_transformation import create_breakpoint
        codegen.extend_output(create_breakpoint())
    """
    __slots__ = ...
    _instance: _BreakpointMarker | None = ...
    def __new__(cls) -> Self:
        ...
    
    def __repr__(self) -> str:
        ...
    


BREAKPOINT_MARKER = ...
@dataclass
class CodeInfo:
    """Per-code-object data shared across all frames executing the same code."""
    code: types.CodeType
    instructions: list[Instruction]
    offset_to_inst: dict[int, Instruction]
    offset_to_index: dict[int, int]
    index_width: int
    offset_width: int
    breakpoints: set[int] = ...


@dataclass
class DebuggerState:
    """Per-frame debugging state."""
    code_info: CodeInfo
    frame: types.FrameType
    current_offset: int = ...
    current_stack_depth: int = ...
    first_instruction_seen: bool = ...
    step_mode: bool = ...
    step_count: int = ...
    user_locals: dict[str, Any] = ...
    last_command: str = ...
    list_index: int | None = ...
    @property
    def code(self) -> types.CodeType:
        ...
    
    @property
    def instructions(self) -> list[Instruction]:
        ...
    
    @property
    def offset_to_inst(self) -> dict[int, Instruction]:
        ...
    
    @property
    def offset_to_index(self) -> dict[int, int]:
        ...
    
    @property
    def index_width(self) -> int:
        ...
    
    @property
    def offset_width(self) -> int:
        ...
    
    @property
    def breakpoints(self) -> set[int]:
        ...
    


class _DebugContext:
    """Internal debug context that manages the debugging session."""
    def __init__(self) -> None:
        ...
    
    def get_instructions(self, code: types.CodeType | None = ...) -> list[Instruction]:
        """Get the list of instructions for a tracked code object.

        Args:
            code: The code object to get instructions for. If None, returns
                  instructions from the most recently tracked code object.

        Returns:
            List of instructions, or empty list if the code is not tracked.
        """
        ...
    
    def get_tracked_codes(self) -> list[types.CodeType]:
        """Get all code objects that have been tracked by the debugger."""
        ...
    
    @staticmethod
    def is_programmatic_breakpoint(inst: Instruction) -> bool:
        ...
    
    def __enter__(self) -> Self:
        """Start the debug context."""
        ...
    
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> bool:
        """End the debug context."""
        ...
    


@contextmanager
def debug() -> Generator[_DebugContext, None, None]:
    """
    Context manager for debugging Dynamo-generated bytecode.

    Any Dynamo-generated code executed within this context will trigger
    the interactive bytecode debugger.

    Example:
        >>> # xdoctest: +SKIP
        >>> import torch
        >>>
        >>> @torch.compile
        >>> def my_fn(x):
        ...     return x + 1
        >>>
        >>> with torch._dynamo.bytecode_debugger.debug():
        ...     my_fn(torch.randn(3))
    """
    ...

def breakpoint() -> None:
    """Programmatic breakpoint for user code.

    Place this in code compiled by Dynamo. During tracing, Dynamo inserts a
    BREAKPOINT_MARKER into the compiled bytecode. When the bytecode debugger
    is active, execution pauses at this marker.
    """
    ...

