"""
This type stub file was generated by pyright.
"""

import dataclasses
from typing import TYPE_CHECKING
from .symbolic_convert import InstructionTranslatorBase
from .bytecode_transformation import Instruction

if TYPE_CHECKING:
    ...
log = ...
@dataclasses.dataclass
class ComprehensionAnalysis:
    """Metadata about a comprehension's bytecode structure.

    Attributes:
        end_ip: Instruction pointer after all comprehension bytecode
        result_var: Name of result variable, or None if result stays on stack
        result_on_stack: True if result stays on stack (discarded, returned, or in expression)
        iterator_vars: Variables from LOAD_FAST_AND_CLEAR (need restoration)
        walrus_vars: Variables assigned via walrus operator (:=) inside comprehension
        captured_vars: Variables read from outer scope via LOAD_FAST inside comprehension
    """
    end_ip: int
    result_var: str | None
    result_on_stack: bool
    iterator_vars: list[str]
    walrus_vars: list[str]
    captured_vars: list[str]
    ...


def maybe_setup_comprehension_speculation(tx: InstructionTranslatorBase, inst: Instruction) -> bool:
    """
    Handle comprehension start for Python 3.12+ BUILD_LIST/BUILD_MAP with argval 0.
    Returns True if a graph break was triggered and the caller should return early.
    """
    ...

