"""
This type stub file was generated by pyright.
"""

from typing import Any, Generic, TYPE_CHECKING, TypeVar
from torch._guards import CompileId

if TYPE_CHECKING:
    ...
log = ...
class GraphIdFilter:
    """
    A filter for matching graph IDs based on various conditions.
    Supports individual IDs, ranges, and comparison operators.
    """
    def __init__(self, filter_str: str) -> None:
        ...
    
    def __contains__(self, graph_id: int) -> bool:
        """Check if the given graph ID matches this filter."""
        ...
    
    def __repr__(self) -> str:
        ...
    


T = TypeVar("T")
class _GraphRouterBase(Generic[T]):
    """
    Base class for routing graphs to different values based on their IDs.

    The router parses a configuration string with rules in the format:
        "filter1:value1;filter2:value2;..."

    Rules are evaluated in order, and the first matching rule wins.
    """
    def __init__(self, config_str: str, rule_type: str) -> None:
        ...
    
    def get_value_for_graph(self, graph_id: int) -> T | None:
        """Get the value for a given graph ID. Returns None if no rule matches."""
        ...
    
    def is_empty(self) -> bool:
        """Check if no rules are configured."""
        ...
    


class GraphBackendRouter(_GraphRouterBase[Any]):
    """
    Routes graphs to different backends based on their IDs.

    The router parses a configuration string with rules in the format:
        "filter1:backend1;filter2:backend2;..."

    If a graph ID matches multiple rules with different backends, a ValueError
    is raised.

    Examples:
        "0-5:eager;>5:inductor"     - IDs 0-5 use eager, rest use inductor
        ">10:aot_eager"             - IDs > 10 use aot_eager
        "<=3:eager;4-10:aot_eager"  - IDs 0-3 use eager, 4-10 use aot_eager

    Supported backends include "eager", "aot_eager", "aot_eager_decomp_partition",
    "inductor", and any other registered backend.
    """
    def __init__(self, config_str: str) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


class GraphConfigRouter(_GraphRouterBase[dict[str, Any]]):
    """
    Routes graphs to different inductor configs based on their IDs.

    The router parses a configuration string with rules in the format:
        "filter1:config1;filter2:config2;..."

    All matching rules are aggregated: configs from all matching rules are merged
    into a single dict. Conflicting keys (same key, different value) raise an error.
    Config format is "key=value" or "key1=value1,key2=value2" for multiple settings.

    Examples:
        "0-5:triton.cudagraph_skip_dynamic_graphs=False"
        ">10:triton.cudagraphs=False,triton.cudagraph_trees=False"

        With "0:a=1;>=0:b=2", graph 0 gets {"a": 1, "b": 2} (both rules match).
        With "0:a=1;>=0:a=2", graph 0 raises an error (conflicting values for "a").
        With "0:a=1;>=0:a=1", graph 0 gets {"a": 1} (same value is not a conflict).
    """
    def __init__(self, config_str: str) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


def get_backend_override_for_compile_id(compile_id: CompileId | None, config_str: str) -> Any:
    """
    Get the backend override for a given CompileId.

    Returns the backend function to use, or None if no override applies.
    """
    ...

def get_inductor_config_override_for_compile_id(compile_id: CompileId | None, config_str: str) -> dict[str, Any] | None:
    """
    Get the inductor config override for a given CompileId.

    Returns a dict of config patches to apply, or None if no override applies.
    """
    ...

def get_dynamo_config_override_for_compile_id(compile_id: CompileId | None, config_str: str) -> dict[str, Any] | None:
    """
    Get the dynamo config override for a given CompileId.

    Returns a dict of config patches to apply, or None if no override applies.
    """
    ...

_create_router = ...
