"""
This type stub file was generated by pyright.
"""

import ast
import dataclasses
import enum
import functools
import pickle
import traceback
import types
import weakref
import torch
import torch.overrides
from typing import Any, NamedTuple, NoReturn, TYPE_CHECKING
from typing_extensions import LiteralString, TypeAliasType, TypeVar
from torch._C._dynamo.guards import DictGuardManager, GuardDebugInfo, GuardManager, LeafGuard, RootGuardManager
from torch._guards import CompileId, Guard, GuardBuilderBase, Source
from torch._inductor.utils import IndentedBuffer
from torch.fx.experimental.symbolic_shapes import _CppShapeGuardsHelper, _ShapeGuardsHelper
from torch.utils._ordered_set import OrderedSet
from .source import AttrSource, DictGetItemSource, DictSubclassGetItemSource
from .types import CacheEntry, DynamoFrameType, GuardFail, GuardFilterEntry, GuardFn
from .utils import normalize_count_iter, normalize_range_iter, tuple_iterator_len
from collections.abc import Callable, Generator, KeysView, Sequence
from torch._C import DispatchKeySet
from torch._dynamo.output_graph import OutputGraphCommon, OutputGraphGuardsState

"""
Core guard system for Dynamo that detects when compiled code needs to be recompiled due to
changes in program state. Guards are conditions that must remain true for previously-compiled
code to be valid for reuse.

This module provides the infrastructure for creating, managing and checking guards, including:
- Guard creation and composition
- Guard state management and invalidation
- Guard checking and failure handling
- Utilities for guard optimization and debugging
- Integration with Dynamo's compilation caching

The guard system is critical for Dynamo's ability to efficiently reuse compiled code while
maintaining correctness by detecting when recompilation is necessary due to changes in
program state, tensor properties, or control flow.
"""
if TYPE_CHECKING:
    ...
guard_manager_testing_hook_fn: Callable[[Any, Any, Any], Any] | None = ...
_COUNT_ITERATOR_TYPE = ...
if TYPE_CHECKING:
    ...
T = TypeVar("T")
log = ...
guards_log = ...
recompiles_log = ...
recompiles_verbose_log = ...
verbose_guards_log = ...
dunder_attrs_assumed_constants = ...
def get_framelocals_idx(code: types.CodeType, var_name: str) -> int:
    ...

class IndentedBufferWithPrefix(IndentedBuffer):
    def prefix(self) -> str:
        ...
    
    def writeline(self, line: str, skip_prefix: bool = ...) -> None:
        ...
    


class GuardManagerWrapper:
    """
    A helper class that contains the root guard manager. An instance of this
    class is stored in the Dynamo cache entry, so that the cache entry can
    access the RootGuardManager stored in the "root" attribute and directly call
    the check_nopybind from C++.
    """
    def __init__(self, root: RootGuardManager | None = ...) -> None:
        ...
    
    def collect_diff_guard_sources(self) -> OrderedSet[str]:
        ...
    
    def finalize(self) -> None:
        ...
    
    def prepare_diff_guard_manager(self) -> None:
        ...
    
    def find_tag_safe_roots(self) -> None:
        """
        Identify ``tag safe nodes`` and ``tag safe roots`` within a guard tree.

        -----------------------------------------------------------------------
        tag safe node
        -----------------------------------------------------------------------
        A *tag safe node* is a ``GuardManager`` whose guarded value satisfies one
        of the following conditions:

        1. Immutable value - The value is intrinsically immutable according to
        ``is_immutable_object``. Tensors are considered immutable. To ensure
        that symbolic guards run, we also check that the GuardManager has no
        accessors.

        2. Nested tag safe dictionary - The value is a ``dict`` whose keys and
        values are all tag safe nodes  (checked recursively).  Such dictionaries
        allow entire nested structures to be skipped once their identity tag
        matches.

        3. Pure ``nn.Module`` - The value is an ``nn.Module`` whose sole
        accessor is ``GetGenericDictGuardAccessor``—i.e., it only exposes its
        ``__dict__`` and nothing else that could mutate between runs.

        For every tag safe node, verifying the identity/tag of just the top-level
        dictionary is enough to guarantee the entire subtree is unchanged, enabling
        a *fast-path* guard check.

        -----------------------------------------------------------------------
        tag safe root
        -----------------------------------------------------------------------
        A ``tag safe root`` is a tag safe node whose parent is not tag safe.
        These boundary nodes mark the points where guard evaluation can safely
        prune traversal: if a tag-safe root's dictionary tag matches, the entire
        subtree beneath it is skipped.

        One strong requirement for tag safe root is for the guarded object to
        support weakref. Refer to more details in the Recursive dict tag
        matching note. In short, we need to save the weakref of the object on
        first invocation, and check if it is still valid in later iterations, to
        apply recursive dict tag optimizations. `dict` objects do NOT support
        weakref. Therefore, as of now, we only mark nn module related guard
        managers as tag safe roots.

        Algorithm
        ---------
        The search runs in post-order traversal

        1. Visit leaves and classify them as tag safe or not.
        2. Propagate tag-safety upward: a parent dictionary becomes tag safe only if
        all of its children are already tag-safe.
        3. Propagate tag-safe-rootness upward: if the whole subtree is tag safe,
        the current node becomes the new tag safe root, otherwise propagate the
        subtree tag safe roots.
        4. Collect every tag safe node and, by inspecting parent tags, label the
        subset that are tag safe roots.
        """
        ...
    
    def populate_diff_guard_manager(self) -> None:
        ...
    
    def clone_with_chosen_sources(self, chosen_sources: OrderedSet[str]) -> RootGuardManager:
        ...
    
    def get_guard_lines(self, guard: LeafGuard) -> list[str]:
        ...
    
    def get_manager_line(self, guard_manager: GuardManager, accessor_str: str | None = ...) -> str:
        ...
    
    def construct_dict_manager_string(self, mgr: DictGuardManager, body: IndentedBufferWithPrefix) -> None:
        ...
    
    def construct_manager_string(self, mgr: GuardManager, body: IndentedBufferWithPrefix) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def check(self, x: Any) -> bool:
        ...
    
    def check_verbose(self, x: Any) -> GuardDebugInfo:
        ...
    
    def populate_code_parts_for_debugging(self) -> None:
        ...
    


def from_numpy(a: Any) -> torch.Tensor:
    ...

@functools.cache
def uninteresting_files() -> set[str]:
    ...

_CLOSURE_VARS: dict[str, object] | None = ...
strip_function_call = ...
def get_verbose_code_part(code_part: str, guard: Guard | None) -> str:
    ...

def get_verbose_code_parts(code_parts: str | list[str], guard: Guard | None, recompile_hint: str | None = ...) -> list[str]:
    ...

def convert_int_to_concrete_values(dim: Any) -> int | None:
    ...

def convert_to_concrete_values(size_or_stride: list[Any]) -> list[int | None]:
    ...

def get_tensor_guard_code_part(value: torch.Tensor, name: str, sizes: list[int | None], strides: list[int | None], pytype: type, dispatch_keys: DispatchKeySet) -> str:
    ...

def get_key_index(dct: dict[Any, Any], key: Any) -> int:
    ...

def get_key_index_source(source: Any, index: Any) -> str:
    ...

def raise_local_type_error(obj: Any) -> NoReturn:
    ...

def should_optimize_getattr_on_nn_module(value: Any) -> bool:
    ...

@dataclasses.dataclass(frozen=True)
class NNModuleAttrAccessorInfo:
    present_in_generic_dict: bool = ...
    l1_key: str | None = ...
    l2_key: str | None = ...


def getitem_on_dict_manager(source: DictGetItemSource | DictSubclassGetItemSource, base_guard_manager: DictGuardManager, base_example_value: Any, example_value: Any, guard_manager_enum: GuardManagerType) -> GuardManager:
    ...

def match_on_id_for_tensor(guard: Guard) -> bool:
    ...

@dataclasses.dataclass
class GuardCodeList:
    code_list: list[str]
    guard: Guard
    ...


class GuardManagerType(enum.Enum):
    GUARD_MANAGER = ...
    DICT_GUARD_MANAGER = ...


@functools.cache
def code_framelocals_names_reversed_cached(code: types.CodeType) -> list[str]:
    ...

class GuardCheckSpec(NamedTuple):
    """Lightweight guard evaluation for subgraph reuse during tracing.

    WHY IS THIS NEEDED?
    Normal guards are collected during tracing, installed via GuardBuilder, and
    evaluated in C++ at runtime. GuardCheckSpec serves a different purpose: we
    want to evaluate a guard *during tracing* to check whether a previously
    traced partial subgraph can be reused. The guard is collected during the
    first trace of subgraph and then evaluated with a new source value before we
    begin tracing the second subgraph.

    Existing C++ guards don't satisfy this need because they're designed for
    runtime evaluation, not mid-trace comparisons with different source values.

    NB - This separate spec table *increases maintenance burden*, but each
    handler is small and the number of guard types is finite, so it's tractable.

    get_metadata_fn: (guard, value) -> metadata  — captures the minimum
        information from the guarded value at build time.
    eval_fn: (value, metadata) -> bool  — re-evaluates the guard at lookup
        time using a fresh value and the previously saved metadata.
    """
    get_metadata_fn: Any
    eval_fn: Any
    ...


SKIP_GUARD = ...
def extract_tensor_metadata(t: torch.Tensor) -> tuple[Any, ...]:
    ...

def extract_subclass_metadata(guard: Any, value: Any) -> tuple[Any, ...]:
    ...

def check_subclass_metadata(value: Any, metadata: tuple[Any, ...]) -> bool:
    ...

def extract_dtensor_spec(guard: Any, value: Any) -> Any:
    ...

def check_dtensor_spec(value: Any, metadata: Any) -> bool:
    ...

def extract_opaque_obj(guard: Any, value: Any) -> Any:
    ...

def check_opaque_obj(value: Any, metadata: Any) -> bool:
    ...

def extract_closure(guard: Any, value: Any) -> Any:
    ...

def check_closure(value: Any, metadata: Any) -> bool:
    ...

def register_guard_check_spec(get_metadata_fn, eval_fn): # -> Callable[..., Any]:
    """Attach a GuardCheckSpec to a guard method for auto-dispatch."""
    ...

def skip_guard_check_spec(fn):
    """Mark a guard method as skipped during auto-cache dispatch."""
    ...

class UnsupportedGuardCheckSpec:
    """Sentinel for guards with no check spec yet.

    Raises NotImplementedError if get_metadata_fn/eval_fn are accidentally called.
    """
    def __init__(self, name: str) -> None:
        ...
    
    @property
    def get_metadata_fn(self):
        ...
    
    @property
    def eval_fn(self):
        ...
    


def unsupported_guard_check_spec(fn):
    """Mark a guard method as unsupported for auto-cache dispatch."""
    ...

class GuardBuilder(GuardBuilderBase):
    def __init__(self, f_code: types.CodeType, id_ref: Callable[[object, str], int], source_ref: Callable[[Source], str], lookup_weakrefs: Callable[[object], weakref.ref[object] | None], local_scope: dict[str, object], global_scope: dict[str, object], guard_manager: GuardManagerWrapper, check_fn_manager: CheckFunctionManager, save_guards: bool = ..., runtime_global_scope: dict[str, object] | None = ..., guard_filter_fn: Callable[[Sequence[GuardFilterEntry]], Sequence[bool]] | None = ...) -> None:
        ...
    
    def guard_on_dict_keys_and_ignore_order(self, example_value: dict[Any, Any], guard: Guard) -> None:
        ...
    
    def guard_on_dict_keys_and_order(self, value: dict[Any, Any], guard: Guard) -> None:
        ...
    
    def getattr_on_nn_module(self, source: AttrSource, base_guard_manager: GuardManager, base_example_value: Any, example_value: Any, base_source_name: str, source_name: str, guard_manager_enum: GuardManagerType) -> GuardManager:
        """
        This tries to avoid calling the expensive nn module custom getattr method by
        checking if the attribute is accessible via __dict__. For attributes that
        are not accessible via __dict__ (like descriptors), we fallback to
        PyObject_GetAttr.

        There are two cases that we optimize for
        1) attributes present directly in __dict__, e.g training.
        2) parameters/buffers/modules - they can be accessed via _parameters,
        _buffers, _modules keys in __dict__. For example, mod.linear can be
        accessed as mod.__dict__["_parameters"]["linear"]

        The most common and expensive case for nn module guards is of type
        mod.submod1.submod2.submod3.training. We avoid the python getattr of nn
        modules by going through the __dict__.
        """
        ...
    
    def requires_key_order_guarding(self, source: Source) -> bool:
        ...
    
    def get_guard_manager_type(self, source: Source, example_value: KeysView[Any] | set[Any] | frozenset[Any] | dict[Any, Any] | None) -> GuardManagerType:
        ...
    
    def manager_guards_on_keys(self, mgr_enum: GuardManagerType) -> bool:
        ...
    
    def get_global_guard_manager(self) -> GuardManager:
        ...
    
    def get_guard_manager_from_source(self, source: Source) -> GuardManager:
        ...
    
    def get_guard_manager(self, guard: Guard) -> GuardManager:
        ...
    
    def add_python_lambda_leaf_guard_to_root(self, code_parts: list[str], verbose_code_parts: list[str], closure_vars: dict[str, object] | None = ..., is_epilogue: bool = ...) -> None:
        ...
    
    def get(self, guard_or_source: Guard | Source, closure_vars: dict[str, Any] | None = ...) -> Any:
        ...
    
    def arg_ref(self, guard: str | Guard) -> str:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: (guard.create_fn.keywords["attr"], hasattr(value, guard.create_fn.keywords["attr"])), eval_fn=lambda value, metadata: hasattr(value, metadata[0]) == metadata[1])
    def HASATTR(self, guard: Guard, attr: str | None = ...) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: guard.create_fn.keywords["attr"], eval_fn=lambda value, metadata: metadata not in value.__dict__)
    def NOT_PRESENT_IN_GENERIC_DICT(self, guard: Guard, attr: Any | None = ...) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: type(value), eval_fn=lambda value, metadata: type(value) is metadata)
    def TYPE_MATCH(self, guard: Guard) -> None:
        ...
    
    @unsupported_guard_check_spec
    def DICT_VERSION(self, guard: Guard) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: guard.create_fn.keywords["key"], eval_fn=lambda value, metadata: metadata in value)
    def DICT_CONTAINS(self, guard: Guard, key: str) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: guard.create_fn.keywords["key"], eval_fn=lambda value, metadata: metadata not in value)
    def DICT_NOT_CONTAINS(self, guard: Guard, key: str) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: guard.create_fn.keywords["key"], eval_fn=lambda value, metadata: metadata in value)
    def SET_CONTAINS(self, guard: Guard, key: Any) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: guard.create_fn.keywords["key"], eval_fn=lambda value, metadata: metadata not in value)
    def SET_NOT_CONTAINS(self, guard: Guard, key: Any) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: value, eval_fn=lambda value, metadata: value == metadata)
    def BOOL_MATCH(self, guard: Guard) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: None, eval_fn=lambda value, metadata: value is None)
    def NONE_MATCH(self, guard: Guard) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: value, eval_fn=lambda value, metadata: value is metadata)
    def ID_MATCH(self, guard: Guard, recompile_hint: str | None = ...) -> None:
        ...
    
    def id_match_unchecked(self, guard: Guard, recompile_hint: str | None = ...) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: None, eval_fn=lambda value, metadata: value is not None)
    def NOT_NONE_MATCH(self, guard: Guard, value: Any | None = ...) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: value.raw_repr(), eval_fn=lambda value, metadata: value.raw_repr() == metadata)
    def DISPATCH_KEY_SET_MATCH(self, guard: Guard) -> None:
        ...
    
    @skip_guard_check_spec
    def DUAL_LEVEL(self, guard: Guard) -> None:
        ...
    
    @skip_guard_check_spec
    def FUNCTORCH_STACK_MATCH(self, guard: Guard) -> None:
        ...
    
    @skip_guard_check_spec
    def AUTOGRAD_SAVED_TENSORS_HOOKS(self, guard: Guard) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=extract_subclass_metadata, eval_fn=check_subclass_metadata)
    def TENSOR_SUBCLASS_METADATA_MATCH(self, guard: Guard) -> None:
        class _AnyCompare:
            ...
        
        
    
    @register_guard_check_spec(get_metadata_fn=extract_dtensor_spec, eval_fn=check_dtensor_spec)
    def DTENSOR_SPEC_MATCH(self, guard: Guard) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=extract_opaque_obj, eval_fn=check_opaque_obj)
    def OPAQUE_OBJ_GUARD_FN_MATCH(self, guard: Guard) -> None:
        """Guard on the values returned by the opaque object's guard_fn."""
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: value, eval_fn=lambda value, metadata: value == metadata)
    def EQUALS_MATCH(self, guard: Guard, recompile_hint: str | None = ...) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: value, eval_fn=lambda value, metadata: value == metadata)
    def CONSTANT_MATCH(self, guard: Guard) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: _constant_subclass_base_value(value), eval_fn=lambda value, metadata: _constant_subclass_base_value(value) == metadata)
    def CONSTANT_SUBCLASS_MATCH(self, guard: Guard) -> None:
        """Guard for subclasses of constant types (int, float, str, etc.).

        Extracts the base value using the base type's converter (e.g.,
        int.__int__) to avoid calling user-overridden __eq__.
        """
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: value, eval_fn=lambda value, metadata: value is metadata)
    def NN_MODULE(self, guard: Guard) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: value, eval_fn=lambda value, metadata: value is metadata)
    def FUNCTION_MATCH(self, guard: Guard) -> None:
        """things like torch.add and user defined functions"""
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: value, eval_fn=lambda value, metadata: value is metadata)
    def CLASS_MATCH(self, guard: Guard) -> None:
        """Equals ID_MATCH on classes - better readability than directly calling ID_MATCH"""
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: value, eval_fn=lambda value, metadata: value is metadata)
    def MODULE_MATCH(self, guard: Guard) -> None:
        """Equals ID_MATCH on modules - better readability than directly calling ID_MATCH"""
        ...
    
    @register_guard_check_spec(get_metadata_fn=extract_closure, eval_fn=check_closure)
    def CLOSURE_MATCH(self, guard: Guard) -> None:
        """matches a closure by __code__ id."""
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: value, eval_fn=lambda value, metadata: value is metadata)
    def BUILTIN_MATCH(self, guard: Guard) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: len(value), eval_fn=lambda value, metadata: len(value) == metadata)
    def SEQUENCE_LENGTH(self, guard: Guard) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: tuple_iterator_len(value), eval_fn=lambda value, metadata: tuple_iterator_len(value) == metadata)
    def TUPLE_ITERATOR_LEN(self, guard: Guard) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: normalize_range_iter(value), eval_fn=lambda value, metadata: normalize_range_iter(value) == metadata)
    def RANGE_ITERATOR_MATCH(self, guard: Guard) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: (type(value), normalize_count_iter(value)), eval_fn=lambda value, metadata: (type(value) is metadata[0] and normalize_count_iter(value) == metadata[1]))
    def COUNT_ITERATOR_MATCH(self, guard: Guard) -> None:
        ...
    
    @skip_guard_check_spec
    def DUPLICATE_INPUT(self, guard: Guard, source_b: Source) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: None, eval_fn=lambda value, metadata: value is not None)
    def WEAKREF_ALIVE(self, guard: Guard) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: list(value.keys()), eval_fn=lambda value, metadata: list(value.keys()) == metadata)
    def MAPPING_KEYS_CHECK(self, guard: Guard) -> None:
        """Guard on the key order of types.MappingProxyType object"""
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: list(dict.keys(value)), eval_fn=lambda value, metadata: list(dict.keys(value)) == metadata)
    def DICT_KEYS_MATCH(self, guard: Guard) -> None:
        """Insert guard to check that the keys of a dict are same"""
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: None, eval_fn=lambda value, metadata: len(value) == 0)
    def EMPTY_NN_MODULE_HOOKS_DICT(self, guard: Guard) -> None:
        """Special guard to skip guards on empty hooks. This is controlled by skip_nnmodule_hook_guards"""
        ...
    
    @skip_guard_check_spec
    def GRAD_MODE(self, guard: Guard) -> None:
        ...
    
    @skip_guard_check_spec
    def DETERMINISTIC_ALGORITHMS(self, guard: Guard) -> None:
        ...
    
    @skip_guard_check_spec
    def FSDP_TRAINING_STATE(self, guard: Guard) -> None:
        ...
    
    @skip_guard_check_spec
    def GLOBAL_STATE(self, guard: Guard) -> None:
        ...
    
    @skip_guard_check_spec
    def TORCH_FUNCTION_STATE(self, guard: Guard) -> None:
        ...
    
    @skip_guard_check_spec
    def DEFAULT_DEVICE(self, guard: Guard) -> None:
        """Guard on CURRENT_DEVICE per torch.utils._device"""
        ...
    
    @skip_guard_check_spec
    def SHAPE_ENV(self, guard: Guard) -> None:
        ...
    
    @register_guard_check_spec(get_metadata_fn=lambda guard, value: extract_tensor_metadata(value), eval_fn=lambda value, metadata: (isinstance(value, torch.Tensor) and extract_tensor_metadata(value) == metadata))
    def TENSOR_MATCH(self, guard: Guard, value: Any | None = ...) -> None:
        ...
    


class PyExprCSEPass:
    USE_THRESHOLD = ...
    ALLOWED_NODE_TYPES = ...
    @dataclasses.dataclass
    class Config:
        expr_count: dict[str, int]
        expr_to_name: dict[str, str]
        ...
    
    
    class ExprCounter(ast.NodeVisitor):
        def __init__(self, config: PyExprCSEPass.Config) -> None:
            ...
        
        def visit(self, node: ast.AST) -> None:
            ...
        
    
    
    class Replacer(ast.NodeTransformer):
        def __init__(self, config: PyExprCSEPass.Config, gen_name: Callable[[], str]) -> None:
            ...
        
        def visit(self, node: ast.AST) -> Any:
            ...
        
    
    
    def __init__(self) -> None:
        ...
    
    def count(self, exprs: list[str]) -> None:
        ...
    
    def replace(self, expr: str) -> tuple[list[str], str]:
        ...
    


def must_add_nn_module_guards(guard: Guard) -> bool:
    ...

class DeletedGuardManagerWrapper(GuardManagerWrapper):
    def __init__(self, reason: str) -> None:
        ...
    
    def populate_diff_guard_manager(self) -> None:
        ...
    


@dataclasses.dataclass
class ShapeCodeParts:
    python_code_parts: _ShapeGuardsHelper
    verbose_code_parts: _ShapeGuardsHelper
    cpp_code_parts: _CppShapeGuardsHelper | None
    python_fallback: bool
    shape_env_sources: list[Source]
    ...


@dataclasses.dataclass
class GuardsState:
    output_graph: OutputGraphGuardsState
    shape_code_parts: ShapeCodeParts | None
    ...


class _Missing:
    def __init__(self, reason: str | None = ...) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        ...
    


class GuardsStatePickler(pickle.Pickler):
    def __init__(self, guard_tree_values: dict[int, Any], empty_values: dict[int, Any], missing_values: dict[int, Any], *args: Any, **kwargs: Any) -> None:
        ...
    
    def reducer_override(self, obj: Any) -> tuple[Callable[..., Any], tuple[Any, ...]] | Any:
        ...
    


def make_guard_filter_entry(guard: Guard, builder: GuardBuilder) -> GuardFilterEntry:
    ...

def pickle_guards_state(state: GuardsState, builder: GuardBuilder) -> bytes:
    ...

class CheckFunctionManager:
    def __init__(self, f_code: types.CodeType, output_graph: OutputGraphCommon, cache_entry: CacheEntry | None = ..., guard_fail_fn: Callable[[GuardFail], None] | None = ..., guard_filter_fn: Callable[[Sequence[GuardFilterEntry]], Sequence[bool]] | None = ..., shape_code_parts: ShapeCodeParts | None = ..., runtime_global_scope: dict[str, Any] | None = ..., save_guards: bool = ..., strict_error: bool = ...) -> None:
        ...
    
    UNSUPPORTED_SERIALIZATION_GUARD_TYPES: tuple[LiteralString, ...] = ...
    def serialize_guards(self, builder: GuardBuilder, sorted_guards: list[Guard], output_graph: OutputGraphCommon) -> bytes:
        ...
    
    def build_guards(self, sorted_guards: list[Guard], existing_diff_guard_sources: OrderedSet[str], f_code: types.CodeType, output_graph: OutputGraphGuardsState, save_guards: bool, guard_filter_fn: Callable[[Sequence[GuardFilterEntry]], Sequence[bool]] | None = ...) -> tuple[GuardBuilder, GuardManagerWrapper]:
        ...
    
    def compile_check_fn(self, builder: GuardBuilder, guards_out: list[Guard], guard_fail_fn: Callable[[GuardFail], None] | None) -> None:
        ...
    
    def invalidate(self, obj_str: str) -> None:
        ...
    
    def id_ref(self, obj: object, obj_str: str) -> int:
        """add a weakref, return the id"""
        ...
    
    def lookup_weakrefs(self, obj: object) -> weakref.ref[object] | None:
        """Lookup the _weakrefs created in id_ref function for ID_MATCH'd objects"""
        ...
    


def build_guard_function(code_parts: list[str], closure_args: str) -> tuple[str, str]:
    ...

def is_recompiles_enabled() -> bool:
    ...

def is_recompiles_verbose_enabled() -> bool:
    ...

def make_torch_function_mode_stack_guard(initial_stack: list[torch.overrides.TorchFunctionMode]) -> Callable[[], bool]:
    ...

Scope = TypeAliasType("Scope", dict[str, object])
def recompilation_reason_for_no_tensor_aliasing_guard(guard_manager: GuardManagerWrapper, scope: Scope) -> list[str]:
    ...

def strip_local_scope(s: str) -> str:
    """
    Replace occurrences of L[...] with just the inner content.
    Handles both single and double quotes.

    This is to generate user friendly recompilation messages.
    """
    ...

def format_user_stack_trace(user_stack: traceback.StackSummary | None) -> str:
    """
    Format the user stack trace for display in guard failure messages.

    Returns a formatted string representation of the stack trace,
    or an empty string if no user stack is available.
    """
    ...

def get_guard_fail_reason_helper(guard_manager: GuardManagerWrapper, f_locals: dict[str, object], compile_id: CompileId | None, backend: Callable | None) -> str:
    """
    Return the reason why `guard_manager` failed.
    Updates `guard_failures` with the generated reason.
    Only the first failed check of guard_manager is reported.
    """
    ...

def get_guard_fail_reason(guard_manager: GuardManagerWrapper, code: types.CodeType, f_locals: dict[str, object], compile_id: CompileId, backend: Callable, skip_logging: bool = ...) -> str:
    ...

def get_and_maybe_log_recompilation_reasons(cache_entry: CacheEntry | None, frame: DynamoFrameType, backend: Callable, skip_logging: bool = ...) -> list[str]:
    """
    Return the list of guard failure reasons using cache_entry.
    Logs the recompilation reason if `recompiles` logging is enabled.
    Raises a RecompileError if `config.error_on_recompile` is enabled.
    """
    ...

def update_diff_guard_managers_for_existing_cache_entries(cache_entry: CacheEntry | None) -> OrderedSet[str]:
    ...

def guard_error_hook(guard_manager: GuardFn, code: types.CodeType, f_locals: dict[str, object], index: int, last: bool) -> None:
    ...

def unique(seq: Sequence[T]) -> Generator[T, None, None]:
    ...

def make_dupe_guard(obj_source: Source, dupe_source: Source | None) -> functools.partial[Any] | None:
    ...

def install_guard(*guards: Guard, skip: int = ...) -> None:
    """
    Add dynamo guards to the current tracing context.

    Args:
        guards: guard(s) to add
        skip: number of stack frames to ignore for debug stack trace
    """
    ...

GUARD_VALUE_DISPATCH: dict[str, GuardCheckSpec | object] = ...
MISSING_GUARD_SPECS = ...
if MISSING_GUARD_SPECS:
    ...
