"""
This type stub file was generated by pyright.
"""

import torch
from collections.abc import Callable, Sequence
from typing import TypeAlias
from torch.fx import Node
from .core import log

aten = ...
prims = ...
_HandlerType: TypeAlias = Callable[[Node], bool]
propagate_rules: dict[torch._ops.OpOverload, _HandlerType] = ...
def register_propagate_rule(aten_op: torch._ops.OpOverload | Sequence[torch._ops.OpOverload]) -> Callable[[_HandlerType], _HandlerType]:
    ...

def propagate_scale_by(nodes_with_chunking_meta: Sequence[Node]) -> None:
    """
    The input is a list of nodes that have chunking metadata.
    The nodes are already sorted in topological order.
    """
    ...

@register_propagate_rule([aten.div.Tensor])
def propagate_div(div_node: Node) -> bool:
    ...

@register_propagate_rule([aten.where.self])
def propagate_where(where_node: Node) -> bool:
    ...

@register_propagate_rule([aten.exp.default, aten.log.default, aten.tanh.default, aten.eq.Tensor])
def propagate_requires_no_scaling(out_node: Node) -> bool:
    """
    For nonlinear ops (exp, log, tanh) scale_by cannot be propagated
    through since f(S*x) != S*f(x). For boolean-output ops (eq) scale_by
    is meaningless. These ops only appear in the chunking subgraph when
    scale_by is None (e.g. the final gradient is 1).
    """
    ...

@register_propagate_rule([aten.mul.Tensor, prims.convert_element_type.default, aten.neg.default, aten.sum.dim_IntList, aten.sum.default, aten.amax.default, aten.mm.default, aten.permute.default, aten.expand.default, aten.squeeze.dim, aten.unsqueeze.default, aten.gather.default, aten.scatter_add.default, aten.view.default])
def propagate_general_copy(out_node: Node) -> bool:
    """
    A rule that holds for multiple ops: the scale_by of the output is
    set to the only scale_by of input nodes or None if no input has scale_by
    set.
    """
    ...

@register_propagate_rule(aten.scatter.value)
def propagate_scatter_value(out_node: Node) -> bool:
    ...

@register_propagate_rule([aten.add.Tensor, aten.sub.Tensor])
def propagate_add_sub(out_node: Node) -> bool:
    """
    The scale_by node of the two arguments must be the same.
    """
    ...

@register_propagate_rule([prims.fma.default])
def propagate_fma(out_node: Node) -> bool:
    ...

