"""
This type stub file was generated by pyright.
"""

import os
from functools import cache
from typing import cast
from . import cutedsl_utils, dsl_registry, ops, registry, triton_utils

@cache
def get_user_ordering_fn() -> registry.UserOrderingFn | None:
    """
    Get a user-supplied graph-ordering function if specified.

    Pass in a `package.submodule.fn` string to the env variable
    `TORCH_PYTHON_NATIVE_USER_GRAPH_ORDER_FN` that implements the
    calling API described in `torch/_native/README.md`. This function
    must be part of an importable path.

    Return either the imported function or `None`
    """
    ...

user_order_fn = ...
if user_order_fn:
    ...
