"""
This type stub file was generated by pyright.
"""

import torch.library
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from typing import Concatenate, ParamSpec, TypeVar

__all__ = ["UserOrderingFn", "register_op_override", "reorder_graphs_from_user_function", "reenable_op_overrides", "deregister_op_overrides", "get_dsl_operations"]
log = ...
P = ParamSpec("P")
R = TypeVar("R")
_OpOverrideFn = Callable[Concatenate[torch.DispatchKeySet, P], R]
_OpReplaceFn = Callable[P, R]
_OpFn = _OpOverrideFn | _OpReplaceFn
@dataclass
class _OverrideNode:
    """Track function override data."""
    dsl_name: str
    op_symbol: str
    dispatch_key: str
    override_fn: _OpFn
    unconditional_override: bool = ...
    active: bool = ...


UserOrderingFn = Callable[[str, str, list[_OverrideNode]], list[_OverrideNode]]
@dataclass
class _FilterState:
    """Manages filtering state for override nodes."""
    _dsl_names: set[str] = ...
    _op_symbols: set[str] = ...
    _dispatch_keys: set[str] = ...
    def check_enabled(self, node: _OverrideNode) -> bool:
        """
        Check if a node is enabled based on current filter state.

        Args:
            node: The override node to check

        Returns:
            bool: True if the node should be enabled, False if filtered out
        """
        ...
    
    def update(self, dsl_names: str | Iterable[str] | None, op_symbols: str | Iterable[str] | None, dispatch_keys: str | Iterable[str] | None, remove_keys: bool = ...) -> None:
        """
        Update filter sets as (current | new) or (current ~ new).

        Args:
            dsl_names: DSL names to add/remove from filter
            op_symbols: Operation symbols to add/remove from filter
            dispatch_keys: Dispatch keys to add/remove from filter
            remove_keys: If True, remove keys from filter; if False, add them

        Note:
            Uses set.discard as it doesn't raise an exception if the element
            wasn't in the set to begin with.
        """
        ...
    
    def build_disable_key_set(self) -> set[tuple[str, str]]:
        """
        Build a set of dictionary keys based on the current filter state.

        Returns:
            set[tuple[str, str]]: Set of (op_symbol, dispatch_key) tuples
        """
        ...
    
    def __str__(self) -> str:
        """Return string representation of filter state."""
        ...
    


_filter_state: _FilterState = ...
_libs: dict[tuple[str, str], torch.library.Library] = ...
_GraphsType = dict[tuple[str, str], list[_OverrideNode]]
_graphs: _GraphsType = ...
_MappingType = dict[str, list[tuple[str, str]]]
_dsl_name_to_lib_graph: _MappingType = ...
_dispatch_key_to_lib_graph: _MappingType = ...
_op_symbol_to_lib_graph: _MappingType = ...
def reenable_op_overrides(*, enable_dsl_names: str | list[str] | None = ..., enable_op_symbols: str | list[str] | None = ..., enable_dispatch_keys: str | list[str] | None = ...) -> None:
    """
    Re-enable overrides by removing them from filter state and reregistering.

    Args:
        enable_dsl_names: DSL names to re-enable
        enable_op_symbols: Operation symbols to re-enable
        enable_dispatch_keys: Dispatch keys to re-enable

    Note:
        This function uses reverse filter state management (removing from
        filters to enable).
    """
    ...

def deregister_op_overrides(*, disable_dsl_names: str | list[str] | None = ..., disable_op_symbols: str | list[str] | None = ..., disable_dispatch_keys: str | list[str] | None = ...) -> None:
    """
    De-register overrides by updating filter state and reregistering graphs.

    Args:
        disable_dsl_names: DSL names to disable
        disable_op_symbols: Operation symbols to disable
        disable_dispatch_keys: Dispatch keys to disable

    Note:
        This function uses filter state management to selectively disable
        operations.
    """
    ...

def get_dsl_operations(dsl_name: str) -> list[str]:
    """Get list of operations registered by a specific DSL.

    Args:
        dsl_name: Name of the DSL to query.

    Returns:
        Sorted list of operation names registered by the DSL.
    """
    ...

def register_op_override(backend: str, lib_symbol: str, op_symbol: str, dispatch_key: str, impl: _OpOverrideFn | _OpReplaceFn, *, allow_multiple_override: bool = ..., unconditional_override: bool = ...) -> None:
    """
    Register a passed override function to the dispatcher.

    Actually a graph-building operation; real registration happens later.

    Args:
        backend: The backend name (DSL name)
        lib_symbol: Library you're overriding symbols in (must be "aten")
        op_symbol: Name of the operation you're overriding
        dispatch_key: Dispatch key to override
        impl: Implementation function for the override
        allow_multiple_override: Allow overriding an existing override
        unconditional_override: Implementation doesn't have a fallback and
            doesn't require torch.DispatchKeySet as the first argument

    Raises:
        ValueError: If lib_symbol is not "aten"
    """
    ...

def reorder_graphs_from_user_function(fn: UserOrderingFn, *, reregister_overrides: bool = ...) -> None:
    """
    Reorder override graphs using a user-provided ordering function.

    Args:
        fn: User-provided function that takes (op_symbol, dispatch_key, graph)
            and returns a reordered graph
        reregister_overrides: Whether to reregister graphs that have changed

    Note:
        This function uses the common graph transformation pattern and can serve
        as an example for other graph manipulation operations.
    """
    ...

