"""
This type stub file was generated by pyright.
"""

from torch._vendor.packaging.version import Version
from .registry import _OpFn

log = ...
_TRITON_DSL_NAME = ...
_TRITON_REQUIRED_VERSION_MAJOR = ...
_TRITON_MINIMUM_VERSION_MINOR = ...
def runtime_available() -> bool:
    ...

def runtime_version() -> None | Version:
    ...

def deregister_op_overrides() -> None:
    """
    Deregister all ops through triton
    """
    ...

def register_op_override(lib_symbol: str, op_symbol: str, dispatch_key: str, impl: _OpFn, *, allow_multiple_override: bool = ..., unconditional_override: bool = ...) -> None:
    """
    See torch/_native/registry.py for the underlying implementation
    and arguments. This is a thin, DSL-checking wrapper over
    _register_op_override_impl
    """
    ...

