"""
This type stub file was generated by pyright.
"""

import torch
from collections import defaultdict
from contextlib import contextmanager
from typing import Any

"""Annotate CUDA graph kernel nodes during capture.

During CUDA graph capture, ``mark_kernels`` uses ``cudaGraphGetNodes``
to count nodes before and after the wrapped region.  Nodes at indices
``[before, after)`` are the ones added within the scope.  Each kernel
or memcpy node found is annotated by its ``toolsId`` so it can later
be matched to profiler trace events.

The annotations can be pickled and later merged into a Chrome profiler
trace using ``torch.cuda._annotate_cuda_graph_trace``.

Requires ``cuda.bindings`` package and a CUDA driver that supports
``cudaGraphNodeGetToolsId`` (CUDA >= 13.1 or appropriate cuda-compat).
When unavailable, ``mark_kernels`` silently becomes a no-op.

Usage during capture::

    from torch.cuda._graph_annotations import (
        enable_annotations,
        mark_kernels,
        resolve_pending_annotations,
        remap_to_exec_graph,
    )

    enable_annotations()

    with torch.cuda.graph(graph):
        with mark_kernels("phase_A"):
            y = workload_a(x)
        with mark_kernels("phase_B"):
            z = workload_b(y)
        resolve_pending_annotations()

    remap_to_exec_graph(graph)
"""
logger = ...
_tools_id_available: bool | None = ...
_annotations_enabled: bool = ...
def enable_annotations() -> None:
    """Enable kernel annotation recording."""
    ...

def disable_annotations() -> None:
    """Disable kernel annotation recording."""
    ...

_kernel_annotations: defaultdict[int, list[Any]] = ...
_ANNOTATABLE_TYPES: set[Any] | None = ...
_pending_scopes: list[tuple[Any, int, int]] = ...
_capture_graph: Any = ...
_last_capture_graph_id: int | None = ...
@contextmanager
def mark_kernels(annotation: str | dict[str, Any]): # -> Generator[None, Any, None]:
    """Context manager that records node index ranges for later annotation.

    During capture, calls ``cudaGraphGetNodes`` to count graph nodes before
    and after the scope.  Nodes at indices ``[before, after)`` were added
    inside the scope.  After capture, ``resolve_pending_annotations``
    enumerates all nodes and annotates kernel/memcpy nodes in those ranges.

    Must be called inside an active ``torch.cuda.graph()`` capture.  If the
    current stream is not capturing, or if ``cudaGraphNodeGetToolsId`` is not
    available, the context manager is a no-op.

    Args:
        annotation: Arbitrary object appended to the annotation list for
            every kernel/memcpy node whose index falls within this scope.
    """
    ...

def resolve_pending_annotations() -> None:
    """Resolve pending scope index ranges into kernel annotations.

    Enumerates all graph nodes and annotates kernel/memcpy nodes whose
    indices fall within recorded scope ranges. Must be called while still
    inside the ``torch.cuda.graph()`` capture context.
    """
    ...

def remap_to_exec_graph(torch_cuda_graph: torch.cuda.CUDAGraph) -> None:
    """Remap annotation keys from capture graph ID to exec graph ID.

    During capture, toolsId encodes the capture graph's ID in the upper
    32 bits. After instantiation, the profiler uses the exec graph's ID.
    This function rewrites the keys so annotations match the trace.

    Must be called after the ``torch.cuda.graph()`` context exits.
    """
    ...

def get_kernel_annotations() -> dict[int, list[Any]]:
    """Return the current kernel annotation map (toolsId -> annotations)."""
    ...

def clear_kernel_annotations() -> None:
    """Clear all recorded kernel annotations and pending scopes."""
    ...

_stream_id_counter: int = ...
_stream_id_map: dict[int, int] = ...
def get_stream_for_pg(pg_key: str) -> int:
    """Return a unique stream ID for the given process group key."""
    ...

@contextmanager
def mark_stream(stream: torch.cuda.Stream, annotation: str | dict[str, Any]): # -> Generator[None, Any, None]:
    """Switch to stream, inject its ID into annotation, and mark kernels.

    If *stream* is already the current stream, no stream switch or stream ID
    injection happens — the kernels stay on whatever stream is active (which
    keeps the trace faithful when e.g. FSDP uses the current stream for
    copy-in instead of a separate one).
    """
    ...

