"""
This type stub file was generated by pyright.
"""

import torch

__all__ = ["GreenContext"]
_GreenContext = ...
SUPPORTED = ...
if hasattr(torch._C, "_CUDAGreenContext"):
    _GreenContext = ...
    SUPPORTED = ...
class GreenContext(_GreenContext):
    r"""Wrapper around a CUDA green context.

    .. warning::
       This API is in beta and may change in future releases.
    """
    @staticmethod
    def create(*, num_sms: int | None = ..., workqueue_scope: str | None = ..., workqueue_concurrency_limit: int | None = ..., device_id: int | None = ...) -> _GreenContext:
        r"""Create a CUDA green context.

        At least one of ``num_sms`` or ``workqueue_scope`` must be specified.
        Both can be combined to partition SMs and configure workqueues in the
        same green context.

        Arguments:
            num_sms (int, optional): The number of SMs to use in the green
                context. When ``None``, SMs are not partitioned.
            workqueue_scope (str, optional): Workqueue sharing scope. One of
                ``"device_ctx"`` (shared across all contexts, default driver
                behaviour) or ``"balanced"`` (non-overlapping workqueues with
                other balanced green contexts). When ``None``, no workqueue
                configuration is applied.
            workqueue_concurrency_limit (int, optional): Maximum number of
                concurrent stream-ordered workloads for the workqueue. Requires
                ``workqueue_scope`` to be set.
            device_id (int, optional): The device index of green context.
                When ``None``, the current device is used.
        """
        ...
    
    @staticmethod
    def max_workqueue_concurrency(device_id: int | None = ...) -> int:
        r"""Return the maximum workqueue concurrency limit for the device.

        This queries the device for the default number of concurrent
        stream-ordered workloads supported by workqueue configuration
        resources.

        Arguments:
            device_id (int, optional): The device index to query. When
                ``None``, the current device is used.
        """
        ...
    
    def set_context(self) -> None:
        r"""Make the green context the current context."""
        ...
    
    def pop_context(self) -> None:
        r"""Assuming the green context is the current context, pop it from the
        context stack and restore the previous context.
        """
        ...
    
    def Stream(self) -> torch.cuda.Stream:
        r"""Return the CUDA Stream used by the green context."""
        ...
    


