"""
This type stub file was generated by pyright.
"""

import torch
from torch._library.custom_ops import custom_op

"""Custom ops for async activation offloading between GPU and CPU.

These ops encapsulate stream management internally, producing a clean 2-node
IR pattern (offload/reload + wait_tensor) similar to c10d functional collectives.

A single dedicated transfer stream handles all D2H/H2D copies.
Completion events are keyed by output tensor data_ptr() and stored in a
module-level registry, so ``ao.wait_tensor`` takes only the tensor itself
(plus an optional keepalive).

Offload pattern:
    cpu_tensor = ao.offload(gpu_tensor)
    cpu_tensor = ao.wait_tensor(cpu_tensor, gpu_tensor)
                               (keepalive arg extends gpu_tensor lifetime past the async D2H copy)

Reload pattern:
    gpu_tensor = ao.reload(cpu_tensor, device)
    gpu_tensor = ao.wait_tensor(gpu_tensor)
"""
_transfer_streams: dict[torch.device, torch.Stream] = ...
_wait_registry: dict[int, tuple[torch.Event, torch.device]] = ...
@custom_op("ao::offload", mutates_args=())
def offload(tensor: torch.Tensor) -> torch.Tensor:
    """Async offload a GPU tensor to CPU on the dedicated transfer stream.

    Callers MUST pair this with an ``ao.wait_tensor`` that passes the source GPU
    tensor as ``keepalive`` to extend its lifetime past the async D2H copy.
    Do NOT use ``record_stream`` — it causes memory fragmentation and
    unbounded memory growth.

    Uses pinned-memory allocation + copy_ so the transfer is compatible
    with CUDA graph capture.
    """
    ...

@offload.register_fake
def _(tensor: torch.Tensor) -> torch.Tensor:
    ...

@custom_op("ao::reload", mutates_args=())
def reload(tensor: torch.Tensor, device: torch.device) -> torch.Tensor:
    """Async reload a CPU tensor to GPU on the dedicated transfer stream.

    The GPU tensor is allocated on the compute stream to avoid cross-stream
    allocator ownership issues. The H2D copy runs on the transfer stream.
    The completion event is keyed by the output tensor's data_ptr.
    """
    ...

@reload.register_fake
def _(tensor: torch.Tensor, device: torch.device) -> torch.Tensor:
    ...

_lib = ...
def wait_tensor(tensor: torch.Tensor, keepalive: torch.Tensor | None = ...) -> torch.Tensor:
    """Callable wrapper so ``wait_tensor`` can be imported by name for op registration."""
    ...

