"""
This type stub file was generated by pyright.
"""

import contextlib
import sys
import typing
from collections.abc import Callable, Sequence
from typing import Any, TYPE_CHECKING
from torch.overrides import BaseTorchFunctionMode
from ..source import Source
from .base import VariableTracker
from .constant import ConstantVariable
from torch._dynamo.codegen import PyCodegen
from torch._dynamo.symbolic_convert import InstructionTranslator

"""
Built-in function and type variable tracking for TorchDynamo's symbolic execution.

This module contains variable tracker classes for Python built-in functions, types,
and operations during graph compilation. It handles symbolic execution of:

- Built-in functions (len, getattr, isinstance, etc.)
- Type constructors (int, float, str, list, dict, etc.)
- Built-in operators and methods
- Special Python constructs (super, hasattr, etc.)

Key classes:
- BuiltinVariable: Tracks built-in functions and handles their execution
- TypeVariable: Manages type constructor calls and type checking
- SuperVariable: Handles super() calls in class hierarchies

These variable trackers ensure that built-in Python operations are correctly
handled during symbolic execution, either by executing them directly when safe
or by creating appropriate graph nodes when needed.
"""
if TYPE_CHECKING:
    ...
log = ...
IN_PLACE_DESUGARING_MAP = ...
_BUILTIN_CONSTANT_FOLDABLE_METHODS: dict[type, frozenset[str]] = ...
if sys.version_info >= (3, 14):
    ...
_HandlerCallback = Callable[["InstructionTranslator", typing.Any, typing.Any], VariableTracker | None]
_TrackersType = type[VariableTracker] | tuple[type[VariableTracker], ...]
polyfill_fn_mapping = ...
bin_ops = ...
bin_int_ops = ...
un_int_ops = ...
tensor_and_int_ops = ...
un_ops = ...
_SET_LIKE_OP_SUPPORT: tuple[type[VariableTracker], ...] = ...
BUILTIN_TO_TENSOR_FN_MAP: dict[Callable[..., Any], Callable[..., Any]] = ...
BUILTIN_TO_TENSOR_RFN_MAP: dict[Callable[..., Any], Callable[..., Any]] = ...
def populate_builtin_to_tensor_fn_map() -> None:
    class GetMethodMode(BaseTorchFunctionMode):
        """
        Mode to extract the correct methods from torch function invocations
        (Used to get the correct torch.Tensor methods from builtins)
        """
        ...
    
    

class BaseBuiltinVariable(VariableTracker):
    """
    Common base class for all builtin variable trackers (BuiltinVariable,
    DictBuiltinVariable, IterBuiltinVariable, and future specialized builtins).

    Provides shared implementations for guard installation, hasattr tracing,
    and Python-level hashability/equality.

    Specialized subclasses (e.g. DictBuiltinVariable) set `_fn` as a class
    attribute. BuiltinVariable stores the callable on the instance as `self.fn`
    and overrides as_python_constant / reconstruct / var_getattr accordingly.
    """
    _fn: Any = ...
    @classmethod
    def create_with_source(cls, value: Any, source: Source) -> BaseBuiltinVariable:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def is_python_hashable(self) -> bool:
        ...
    
    def get_python_hash(self) -> int:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    


class BuiltinVariable(BaseBuiltinVariable):
    """
    A VariableTracker that represents a built-in value (functions and operators).
    A lot of the code here assumes it will be a function object.

    The BuiltinVariable class wraps Python built-in functions (like len, isinstance, etc.)
    and operators (like +, -, *, etc.) to enable symbolic execution during tracing. This allows
    Dynamo to properly handle these operations when converting Python code to FX graphs while
    maintaining correct semantics and enabling optimizations.
    """
    _SENTINEL = ...
    _nonvar_fields = ...
    @classmethod
    def create_with_source(cls, value: Any, source: Source) -> BuiltinVariable:
        ...
    
    def can_constant_fold_through(self) -> bool:
        ...
    
    def can_insert_in_graph(self) -> bool:
        ...
    
    MUST_USE_SPECIALIZED: frozenset[Any] = ...
    def __init__(self, fn: Any, **kwargs: Any) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def get_real_python_backed_value(self) -> Any:
        ...
    
    def as_proxy(self) -> Any:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def constant_args(self, *args: VariableTracker, **kwargs: VariableTracker) -> bool:
        ...
    
    def tensor_args(self, *args: VariableTracker) -> bool:
        ...
    
    def tensor_args_type(self, arg_types: list[type]) -> bool:
        ...
    
    def python_and_tensor_constant_only(self, *args: VariableTracker, **kwargs: VariableTracker) -> bool:
        ...
    
    @staticmethod
    def unwrap_unspec_args_kwargs(args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> tuple[list[Any], dict[str, Any]]:
        ...
    
    def has_constant_handler(self, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> bool:
        ...
    
    def call_vars(self, tx: InstructionTranslator, *args: Any) -> VariableTracker:
        ...
    
    def call_locals(self, tx: InstructionTranslator, *args: VariableTracker) -> VariableTracker:
        ...
    
    call_function_handler_cache: dict[tuple[object, ...], Callable[[InstructionTranslator, Sequence[VariableTracker], dict[str, VariableTracker]], VariableTracker,],] = ...
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_int(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_float(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_bool(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_repr(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker | None:
        """Handle repr() on user defined objects."""
        ...
    
    def call_str(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker | None:
        ...
    
    call_min = ...
    call_max = ...
    def call_abs(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker:
        ...
    
    def call_pos(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker:
        ...
    
    def call_index(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker:
        ...
    
    def call_round(self, tx: InstructionTranslator, arg: VariableTracker, *args: VariableTracker, **kwargs: VariableTracker) -> VariableTracker:
        ...
    
    def call_range(self, tx: InstructionTranslator, *args: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_slice(self, tx: InstructionTranslator, *args: VariableTracker) -> VariableTracker:
        ...
    
    call_tuple = ...
    def call_callable(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_cast(self, _: Any, *args: VariableTracker, **kwargs: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_dir(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_set(self, tx: InstructionTranslator, *args: VariableTracker, **kwargs: VariableTracker) -> VariableTracker:
        ...
    
    def call_frozenset(self, tx: InstructionTranslator, *args: VariableTracker, **kwargs: VariableTracker) -> VariableTracker:
        ...
    
    def call_zip(self, tx: InstructionTranslator, *args: VariableTracker, **kwargs: VariableTracker) -> VariableTracker:
        ...
    
    def call_len(self, tx: InstructionTranslator, *args: VariableTracker, **kwargs: VariableTracker) -> VariableTracker:
        ...
    
    def call_getitem(self, tx: InstructionTranslator, *args: VariableTracker, **kwargs: VariableTracker) -> VariableTracker:
        ...
    
    def call_isinstance(self, tx: InstructionTranslator, arg: VariableTracker, isinstance_type_var: VariableTracker) -> VariableTracker:
        ...
    
    def call_issubclass(self, tx: InstructionTranslator, left_ty: VariableTracker, right_ty: VariableTracker) -> VariableTracker:
        """Checks if first arg is subclass of right arg"""
        ...
    
    def call_super(self, tx: InstructionTranslator, a: VariableTracker, b: VariableTracker) -> VariableTracker:
        ...
    
    def call_next(self, tx: InstructionTranslator, *args: VariableTracker) -> VariableTracker:
        ...
    
    def call_hasattr(self, tx: InstructionTranslator, obj: VariableTracker, attr: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_map(self, tx: InstructionTranslator, fn: VariableTracker, *seqs: VariableTracker, **kwargs: VariableTracker) -> VariableTracker:
        ...
    
    def call_filter(self, tx: InstructionTranslator, fn: VariableTracker, seq: VariableTracker) -> VariableTracker:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def call_getattr(self, tx: InstructionTranslator, obj: VariableTracker, name_var: VariableTracker, default: VariableTracker | None = ...) -> VariableTracker | None:
        ...
    
    def call_setattr(self, tx: InstructionTranslator, obj: VariableTracker, name_var: VariableTracker, val: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_delattr(self, tx: InstructionTranslator, obj: VariableTracker, name_var: VariableTracker) -> VariableTracker:
        ...
    
    def call_type(self, tx: InstructionTranslator, obj: VariableTracker) -> VariableTracker:
        ...
    
    def call_reversed(self, tx: InstructionTranslator, obj: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_sorted(self, tx: InstructionTranslator, obj: VariableTracker, **kwargs: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_neg(self, tx: InstructionTranslator, a: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_format(self, tx: InstructionTranslator, _format_string: VariableTracker, *args: VariableTracker, **kwargs: VariableTracker) -> VariableTracker:
        ...
    
    def call_id(self, tx: InstructionTranslator, *args: VariableTracker) -> VariableTracker:
        ...
    
    def call_deepcopy(self, tx: InstructionTranslator, x: VariableTracker) -> VariableTracker:
        ...
    
    def call_xor(self, tx: InstructionTranslator, a: VariableTracker, b: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_ixor(self, tx: InstructionTranslator, a: VariableTracker, b: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_sub(self, tx: InstructionTranslator, a: VariableTracker, b: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_isub(self, tx: InstructionTranslator, a: VariableTracker, b: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_and_(self, tx: InstructionTranslator, a: VariableTracker, b: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_iand(self, tx: InstructionTranslator, a: VariableTracker, b: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_or_(self, tx: InstructionTranslator, a: VariableTracker, b: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_ior(self, tx: InstructionTranslator, a: VariableTracker, b: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_not_(self, tx: InstructionTranslator, a: VariableTracker) -> VariableTracker | None:
        ...
    
    def call_contains(self, tx: InstructionTranslator, a: VariableTracker, b: VariableTracker) -> VariableTracker:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    


class DictBuiltinVariable(BaseBuiltinVariable):
    """Variable tracker for the `dict` builtin constructor."""
    _fn = ...
    def __init__(self, value: type = ..., **kwargs: Any) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    @staticmethod
    def call_custom_dict(tx: InstructionTranslator, user_cls: type, /, *args: VariableTracker, **kwargs: VariableTracker) -> VariableTracker:
        ...
    
    @staticmethod
    def call_custom_dict_fromkeys(tx: InstructionTranslator, user_cls: type, /, *args: VariableTracker, **kwargs: VariableTracker) -> VariableTracker:
        ...
    


class IterBuiltinVariable(BaseBuiltinVariable):
    """Variable tracker for the `iter` builtin."""
    _fn = ...
    def __init__(self, value: Any = ..., **kwargs: Any) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class ListBuiltinVariable(BaseBuiltinVariable):
    """Variable tracker for the `list` builtin constructor."""
    _fn = ...
    def __init__(self, value: type = ..., **kwargs: Any) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


@contextlib.contextmanager
def dynamo_disable_grad(tx: InstructionTranslator) -> typing.Iterator[None]:
    ...

