"""
This type stub file was generated by pyright.
"""

import collections
from collections.abc import Callable, Iterator, Sequence
from typing import Any, Literal, TYPE_CHECKING
from .base import VariableTracker
from .constant import ConstantVariable
from .hashable import HashableTracker
from torch._dynamo.codegen import PyCodegen
from torch._dynamo.symbolic_convert import InstructionTranslator
from .functions import UserFunctionVariable

"""
Dictionary-related variable tracking classes for PyTorch Dynamo.

This module implements variable tracking for different types of dictionary-like objects:
- Regular Python dictionaries (dict)
- Ordered dictionaries (collections.OrderedDict)
- Default dictionaries (collections.defaultdict)
- Dictionary views (keys and values)

These classes are responsible for tracking dictionary operations during graph compilation,
maintaining proper guards for dictionary mutations and key existence checks. They handle
dictionary creation, modification, key/value access, and view operations while ensuring
correct behavior in the compiled code through appropriate guard installation.

The implementation uses a special HashableTracker wrapper to handle
dictionary keys while preserving proper aliasing semantics. Set-related classes live
in sets.py.
"""
if TYPE_CHECKING:
    ...
class ConstDictVariable(VariableTracker):
    _cpython_type = ...
    CONTAINS_GUARD = ...
    NOT_CONTAINS_GUARD = ...
    _nonvar_fields = ...
    def __init__(self, items: dict[VariableTracker, VariableTracker], user_cls: type = ..., **kwargs: Any) -> None:
        ...
    
    def as_proxy(self) -> dict[Any, Any]:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    def as_python_constant(self) -> dict[Any, Any]:
        ...
    
    def keys_as_python_constant(self) -> dict[Any, VariableTracker]:
        ...
    
    def python_type(self) -> type:
        ...
    
    def __contains__(self, vt: VariableTracker) -> bool:
        ...
    
    def call_tree_map_branch(self, tx: InstructionTranslator, tree_map_fn: UserFunctionVariable, map_fn: VariableTracker, rest: Sequence[VariableTracker], tree_map_kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_tree_map_with_path_branch(self, tx: InstructionTranslator, tree_map_fn: UserFunctionVariable, map_fn: VariableTracker, rest: Sequence[VariableTracker], tree_map_kwargs: dict[str, VariableTracker], keypath: tuple[Any, ...]) -> VariableTracker:
        ...
    
    def len(self) -> int:
        ...
    
    def has_new_items(self) -> bool:
        ...
    
    def is_new_item(self, value: VariableTracker | None, other: VariableTracker) -> bool:
        ...
    
    def reconstruct_kvs_into_new_dict(self, codegen: PyCodegen) -> None:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def getitem_const_raise_exception_if_absent(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker:
        ...
    
    def getitem_const(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker:
        ...
    
    def maybe_getitem_const(self, arg: VariableTracker) -> VariableTracker | None:
        ...
    
    def realize_key_vt(self, arg: VariableTracker) -> None:
        ...
    
    def install_dict_keys_match_guard(self) -> None:
        ...
    
    def install_dict_contains_guard(self, tx: InstructionTranslator, args: list[VariableTracker]) -> None:
        ...
    
    def mp_subscript_impl(self, tx: InstructionTranslator, key: VariableTracker) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def mp_length(self, tx: InstructionTranslator) -> VariableTracker:
        """Mapping length for dict objects."""
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def clone(self, **kwargs: Any) -> VariableTracker:
        ...
    
    def is_python_hashable(self) -> bool:
        """
        Dictionaries are mutable and therefore not hashable in Python.
        """
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str): # -> Any | VariableTracker:
        ...
    


class MappingProxyVariable(VariableTracker):
    _cpython_type = ...
    def __init__(self, dv_dict: ConstDictVariable, **kwargs: Any) -> None:
        ...
    
    def python_type(self) -> type:
        ...
    
    def unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def mp_subscript_impl(self, tx: InstructionTranslator, key: VariableTracker) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def mp_length(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    


class NNModuleHooksDictVariable(ConstDictVariable):
    def install_dict_keys_match_guard(self) -> None:
        ...
    
    def install_dict_contains_guard(self, tx: InstructionTranslator, args: list[VariableTracker]) -> None:
        ...
    


class DefaultDictVariable(ConstDictVariable):
    _cpython_type = collections.defaultdict
    def __init__(self, items: dict[VariableTracker, VariableTracker], user_cls: type, default_factory: VariableTracker | None = ..., **kwargs: Any) -> None:
        ...
    
    def is_python_constant(self) -> bool:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    @staticmethod
    def is_supported_arg(arg: VariableTracker) -> bool:
        ...
    
    def mp_subscript_impl(self, tx: InstructionTranslator, key: VariableTracker) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


class DictViewVariable(VariableTracker):
    """
    Models _PyDictViewObject

    This is an "abstract" class. Subclasses will override kv and the items method
    """
    kv: str | None = ...
    def __init__(self, dv_dict: ConstDictVariable, **kwargs: Any) -> None:
        ...
    
    @property
    def view_items(self) -> Any:
        ...
    
    @property
    def view_items_vt(self) -> list[VariableTracker]:
        ...
    
    def unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def sq_length(self, tx: InstructionTranslator) -> VariableTracker:
        """Sequence length for dict view objects."""
        ...
    


class DictKeysVariable(DictViewVariable):
    _cpython_type = ...
    kv = ...
    @property
    def set_items(self) -> set[VariableTracker]:
        ...
    
    @property
    def view_items_vt(self) -> list[VariableTracker]:
        ...
    
    def python_type(self) -> type:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class DictValuesVariable(DictViewVariable):
    _cpython_type = ...
    kv = ...
    @property
    def view_items_vt(self) -> list[VariableTracker]:
        ...
    
    def python_type(self) -> type:
        ...
    
    def debug_repr(self) -> str:
        ...
    


class DictItemsVariable(DictViewVariable):
    _cpython_type = ...
    kv = ...
    @property
    def set_items(self) -> set[HashableTracker]:
        ...
    
    @property
    def view_items_vt(self) -> list[VariableTracker]:
        ...
    
    def python_type(self) -> type:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def is_python_hashable(self) -> Literal[False]:
        """
        Dictionary item views are not hashable in Python.
        """
        ...
    


kV = HashableTracker | str
class SideEffectsProxyDict(collections.abc.MutableMapping[kV, VariableTracker]):
    """
    A proxy dict that allows us to track mutations to the dict using side
    effects table as storage.
    """
    @staticmethod
    def get_example_value_dict(vt: VariableTracker) -> dict[str, object]:
        ...
    
    @staticmethod
    def get_value___dict__(tx: InstructionTranslator, vt: VariableTracker) -> dict[str, VariableTracker]:
        ...
    
    def __init__(self, item: VariableTracker, tx: InstructionTranslator) -> None:
        ...
    
    def side_effects_table(self) -> dict[str, VariableTracker]:
        ...
    
    def __getitem__(self, key: kV) -> VariableTracker:
        ...
    
    def __setitem__(self, key: kV, value: VariableTracker) -> None:
        ...
    
    def __delitem__(self, key: kV) -> None:
        ...
    
    def __contains__(self, key: kV) -> bool:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __iter__(self) -> Iterator[HashableTracker]:
        ...
    


class DunderDictVariable(ConstDictVariable):
    """represents object.__dict__"""
    @classmethod
    def create(cls, tx: InstructionTranslator, vt: VariableTracker) -> DunderDictVariable:
        ...
    
    def __init__(self, vt: VariableTracker, tx: InstructionTranslator, **kwargs: Any) -> None:
        ...
    
    def setitem(self, name: str, value: VariableTracker) -> None:
        ...
    
    def getitem(self, name: str) -> VariableTracker:
        ...
    
    def contains(self, name: str) -> bool:
        ...
    
    def getitem_or_default(self, name: str, default: Callable[[], VariableTracker]) -> VariableTracker:
        ...
    
    def install_dict_keys_match_guard(self) -> None:
        ...
    
    def install_dict_contains_guard(self, tx: InstructionTranslator, args: list[VariableTracker]) -> None:
        ...
    


