"""
This type stub file was generated by pyright.
"""

import torch
from typing import Any, Literal, TYPE_CHECKING
from .base import VariableTracker
from torch._dynamo.symbolic_convert import InstructionTranslator

"""
Distributed computing variable tracking classes for PyTorch Dynamo.

This module implements variable tracking for distributed computing components:
- Process Groups (for collective communication)
- Device Meshes (for distributed tensor sharding)
- Placement Types (for specifying distribution strategies)
- Distributed Tensors and their operations
- Backward hooks for distributed module operations

These classes are responsible for tracking distributed operations during graph
compilation while maintaining proper guards and handling distributed-specific
behaviors. They ensure correct handling of distributed components like process
groups, device meshes, and placement strategies while preserving proper semantics
for distributed tensor operations in the compiled code.

The implementation provides special handling for distributed package availability
checks and proper tracking of distributed state and operations across processes.
"""
if TYPE_CHECKING:
    ...
class DistributedVariable(VariableTracker):
    """
    The base distributed variable that encapsulates common methods
    for the distributed objects (i.e. ProcessGroup, DeviceMesh, etc.).
    Concrete distributed objects could inherit this class and add object
    specific logic.

    i.e. It provides the check on the distributed package existence
    and hold the tracking value for the corresponding distributed object.
    """
    def __init__(self, value: Any, **kwargs: Any) -> None:
        ...
    
    def python_type(self) -> type:
        ...
    
    @staticmethod
    def is_available() -> bool:
        ...
    
    def is_python_hashable(self) -> Literal[True]:
        ...
    
    def get_python_hash(self) -> int:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    


def is_from_local(value: object) -> bool:
    ...

def is_constant_pg_functions(value: object) -> bool:
    ...

class WorldMetaClassVariable(DistributedVariable):
    """
    Tracks torch.distributed.GroupMember and torch.distributed.group, which are
    instances of the metaclass _WorldMeta.
    """
    @classmethod
    def is_group_member_type(cls, value: object) -> bool:
        ...
    
    def python_type(self) -> type:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    


class BackwardHookVariable(VariableTracker):
    """
    Handles torch.utils.hooks.BackwardHook for module-level backward
    hooks.
    """
    @staticmethod
    def create(tx: InstructionTranslator, module: VariableTracker, user_hooks: VariableTracker, user_pre_hooks: VariableTracker) -> BackwardHookVariable:
        ...
    
    def __init__(self, proxy: torch.fx.Proxy, module: VariableTracker, user_hooks: VariableTracker, user_pre_hooks: VariableTracker, **options: Any) -> None:
        ...
    
    def as_proxy(self) -> torch.fx.Proxy:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


