"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from .base import VariableTracker
from torch._dynamo.symbolic_convert import InstructionTranslator

"""
Hashability utilities for PyTorch Dynamo variable tracking.

This module provides the HashableTracker wrapper class and associated utilities
for making VariableTracker instances usable as dictionary keys and set elements
during symbolic execution. Used by both ConstDictVariable and SetVariable.
"""
if TYPE_CHECKING:
    ...
def raise_unhashable(arg: VariableTracker, tx: InstructionTranslator | None = ...) -> None:
    ...

def is_hashable(x: VariableTracker) -> bool:
    ...

class HashableTracker:
    """
    Class that wraps a VariableTracker and makes it hashable.
    Note that it's fine to put VTs into dictionaries and sets, but doing so
    does not take into account aliasing.
    """
    _MISSING = ...
    def __init__(self, vt: VariableTracker) -> None:
        ...
    
    def __hash__(self) -> int:
        """
        Computes the hash value for the wrapped VariableTracker.

        For unrealized LazyVariableTrackers, uses the hash of the original value
        to avoid realizing the tracker and inserting unnecessary guards.
        For all other cases, delegates to the VariableTracker's get_python_hash method.

        Returns:
            The hash value of the underlying variable tracker
        """
        ...
    
    def __eq__(self, other: object) -> bool:
        """
        Checks equality between two HashableTracker instances.

        Delegates to the VariableTracker's is_python_equal method to compare
        the underlying variable trackers for Python-level equality.

        Args:
            other: Another HashableTracker instance to compare with

        Returns:
            True if the underlying variable trackers are Python-equal, False otherwise
        """
        ...
    


