"""
This type stub file was generated by pyright.
"""

import enum
import types
import torch
from dataclasses import dataclass
from typing import Any, NamedTuple, TYPE_CHECKING
from torch._dynamo.variables.base import VariableTracker
from torch._dynamo.variables.higher_order_ops import SubgraphTracingInfo, WrapHigherOrderVariable
from torch._guards import InvokeSubgraphReuseCondition, InvokeSubgraphReuseEntry, Source
from torch._higher_order_ops.invoke_subgraph import NestedCompileRegionOptions
from torch.fx.graph_module import GraphModule
from torch.fx.proxy import Proxy
from torch.utils import _pytree as pytree
from torch.utils._ordered_set import OrderedSet
from collections.abc import Sequence
from torch._dynamo.symbolic_convert import InstructionTranslator

"""
This module contains the InvokeSubgraphHigherOrderVariable class and its
supporting helpers for subgraph reuse (auto-cache) in Dynamo's invoke_subgraph
higher-order operator.
"""
if TYPE_CHECKING:
    ...
log = ...
hc_log = ...
class InputTag(enum.Enum):
    TENSOR = ...
    SYMNODE = ...
    CONSTANT = ...
    MODULE = ...


class InputFingerprint(NamedTuple):
    flat_vts: list[tuple[InputTag, VariableTracker]]
    arg_sources: list[Source | None]
    has_unknown: bool = ...
    treespec: pytree.TreeSpec | None = ...


def classify_vt(vt: Any) -> InputTag | None:
    """Return the tag for a leaf VT, or None if unsupported."""
    ...

def build_input_fingerprint(tx: InstructionTranslator, fn_args_vt: Any, kwargs: dict[str, Any]) -> InputFingerprint:
    """Build an InputFingerprint by flattening (args, kwargs) via pytree.

    Uses _make_inlined(tx, pytree.tree_flatten) to recursively flatten
    the argument structure into leaf VTs, classifying each leaf as
    tensor/symnode/constant/module. Also records the TreeSpec so that
    cache lookups can verify structural equivalence.

    Fast path: when kwargs is empty and all args are already leaf VTs
    (tensor/symnode/constant/module), skip the expensive pytree flatten.
    """
    ...

def build_fingerprint_fast(fn_args_vt: Any) -> InputFingerprint:
    """Build fingerprint for the common case of flat leaf args, no kwargs."""
    ...

def build_fingerprint_with_pytree(tx: InstructionTranslator, fn_args_vt: Any, kwargs: dict[str, Any]) -> InputFingerprint:
    """Build fingerprint via pytree flatten for nested/kwargs cases."""
    ...

def get_flat_proxies(fingerprint: InputFingerprint) -> list[Proxy]:
    """Collect deduplicated proxies from tensor/symnode leaves."""
    ...

@dataclass
class LiftedUserArg:
    """Lifted arg that came from a user argument (intermediate activation or explicit input)."""
    index: int
    ...


@dataclass
class LiftedCapturedSource:
    """Lifted arg that is a captured variable (e.g. a weight or parameter) with a Source."""
    source: Any
    ...


@dataclass
class LiftedSyntheticObject:
    """Lifted arg that is a TorchScriptObject with a SyntheticLocalSource."""
    ctor_fn: Any
    ctor_args: tuple[Any, ...]
    ctor_arg_sources: tuple[Any, ...] | None
    ...


@dataclass
class LiftedBoundSymbol:
    """Lifted arg that is a SymInt already bound as a graph input.

    SymInt graph inputs are created during tensor wrapping (not through
    VariableBuilder.wrap_symint), so they aren't registered in
    unspec_variable_map or variable_tracker_cache. Using LiftedCapturedSource
    for these would resolve the source to a concrete Python int via
    source.get_value() instead of reusing the existing symbolic proxy.
    """
    expr: Any
    ...


LiftedArgOrigin = (LiftedUserArg | LiftedCapturedSource | LiftedSyntheticObject | LiftedBoundSymbol)
def get_fn_code(fn_var: Any) -> types.CodeType | None:
    ...

def has_mutated_vars(tx: InstructionTranslator, traced_sources: OrderedSet[Source]) -> bool:
    """Check if any source accessed by the subgraph has been mutated.

    SideEffects.mutated_sources records the exact AttrSource for every
    store_attr call. A simple set intersection with traced_sources tells
    us whether any source the subgraph read was later written to.
    """
    ...

def is_reuse_eligible(tx: InstructionTranslator, body_r: Any, fingerprint: InputFingerprint, tracing_info: SubgraphTracingInfo, traced_sources: OrderedSet[Source] | None = ..., has_reuse_hash_fn: bool = ...) -> bool:
    """Best-effort check for whether a traced subgraph result can be reused.

    It is possible that a subgraph is morally reusable but does not fall
    into the limited support that Dynamo has today. Current limitations:
      - The subgraph must not have side effects.
      - No sourceful variable accessed by the subgraph may have been
        mutated, because guards are snapshotted on source values at trace
        time — if the underlying object changed since then, the cached
        guards would silently evaluate against stale values.
      - Output must be a single tensor, or a tuple/list of plain tensors.
      - All flattened inputs must be one of: tensor, symnode, constant,
        unspecialized NN module — for sourceless or other input types we
        rely on the treespec and tags for structural matching, so only
        types with well-defined comparison semantics are supported.

    When ``has_reuse_hash_fn`` is True, side-effect and mutation checks are
    skipped because the hash key replaces guards — there are no guards to
    go stale from mutations.
    """
    ...

def build_reuse_condition(tx: InstructionTranslator, fingerprint: InputFingerprint, traced_sources: OrderedSet[Source]) -> InvokeSubgraphReuseCondition | None:
    """Build an InvokeSubgraphReuseCondition from a traced subgraph.

    A reuse condition is a mix of two kinds of checks:

    1. **Input tag checks** (from flat_vts): For each flattened leaf VT,
       we record its tag (_VtTag.TENSOR/SYMNODE/CONSTANT/MODULE) and
       metadata (e.g. tensor shape/stride/dtype/device/requires_grad).
       At lookup time, the treespec ensures structural equivalence, and
       then we compare tags and metadata leaf-by-leaf.

    2. **Guard checks** (from traced_sources): During the subgraph trace,
       every source accessed via VariableBuilder is recorded. We look up
       all guards installed on those sources (and on the arg_sources) to
       build the set of guards that must be re-evaluated on cache hit.
       This is more robust than guard diffing because it catches guards
       that were already installed before the subgraph trace began.

    Raise if any guard type is unsupported, as a feedback for compiler
    developers to support that guard type.
    """
    ...

def build_source_replacement(old_arg_sources: list[Source | None], new_arg_sources: list[Source | None]) -> dict[Source, Source]:
    """Map old arg sources to new arg sources for remapping captured variable sources."""
    ...

def is_reusable(tx: InstructionTranslator, condition: InvokeSubgraphReuseCondition, fingerprint: InputFingerprint, cached_entry: InvokeSubgraphReuseEntry) -> bool:
    """Check if a cached subgraph can be reused for the current call.

    Three-phase check:
    (1) Verify that intermediates (tensor metadata, symnode types, constant
        values) match the cached input_checks — these are lightweight
        structural comparisons that don't require source resolution.
    (2) Check for mutations on the remapped traced_sources — if any source
        the subgraph read has been mutated since the original trace, the
        cached guards would evaluate against stale values.
    (3) Build a source replacement mapping (old sources → new sources) and
        re-evaluate the snapshotted guards under the new sources.
    """
    ...

def has_reuse_entries(tx: InstructionTranslator, fn_var: Any) -> bool:
    """Cheap check: does the cache have any entries for this function?"""
    ...

def find_reuse_match(tx: InstructionTranslator, fn_var: Any, fingerprint: InputFingerprint) -> InvokeSubgraphReuseEntry | None:
    ...

def save_reuse_entry(tx: InstructionTranslator, fn_var: Any, fingerprint: InputFingerprint, body_name: str, body_gmod: torch.fx.GraphModule, config: NestedCompileRegionOptions | None, p_args: tuple[Any, ...], body_r: VariableTracker, example_value: Any, max_reuse_entries: int = ..., condition: InvokeSubgraphReuseCondition | None = ..., hash_key: int | None = ...) -> None:
    """Save a traced subgraph into the reuse cache for future cache hits.

    Builds an InvokeSubgraphReuseEntry with the freevar mapping (how each
    lifted arg maps back to user inputs or captured variables), output
    metadata, and arg sources. On a future cache hit, stamp_out_subgraph
    uses this entry to emit a new invoke_subgraph call without re-tracing.

    Exactly one of ``condition`` or ``hash_key`` must be provided.
    ``condition`` stores the entry in the guard-based cache (linear scan);
    ``hash_key`` stores it in the hash-key cache (O(1) lookup).
    """
    ...

def trace_reuse_hash_fn(tx: InstructionTranslator, reuse_hash_fn: Any, fn_args_vt: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> int:
    """Trace the user's reuse_hash_fn to get a constant integer hash key.

    Guards installed during the hash function tracing are skipped — the hash
    key itself is the reuse condition, not the guards.
    """
    ...

def find_reuse_entry_by_key(tx: InstructionTranslator, fn_var: Any, hash_key: int) -> InvokeSubgraphReuseEntry | None:
    ...

def stamp_out_subgraph(tx: InstructionTranslator, fingerprint: InputFingerprint, cached: InvokeSubgraphReuseEntry) -> VariableTracker:
    """Emit a new invoke_subgraph call by stamping out a cached subgraph.

    Sources in the cached entry are parameterized: they refer to the original
    call's sources and must be rewritten to the current call's sources via
    source replacement before we can look up or create the corresponding
    graph placeholders.
    """
    ...

def build_subgraph_input_mapping(tx: InstructionTranslator, p_args: tuple[Any, ...], flat_vts: list[tuple[InputTag, VariableTracker]]) -> list[LiftedArgOrigin]:
    """Build a mapping that records the origin of each lifted arg for a subgraph.

    On a cache hit, we stamp out a new invoke_subgraph call and need to
    reconstruct its argument list in the correct order. Each lifted arg
    (p_args[2:], skipping body_node and body_name) comes from one of:

    - LiftedUserArg: a user argument (intermediate activation or explicit input)
    - LiftedCapturedSource: a captured variable (e.g. a weight or parameter)
    - LiftedSyntheticObject: a TorchScriptObject with a SyntheticLocalSource
    - LiftedBoundSymbol: a SymInt already bound as a graph input
    """
    ...

class InvokeSubgraphHigherOrderVariable(WrapHigherOrderVariable):
    _HOP_NAME = ...
    _ALLOW_FALLBACK_TO_EAGER = ...
    supports_input_mutation = ...
    supports_aliasing = ...
    allow_side_effects = ...
    filter_aliased_intermediates = ...
    def install_subgraph_in_output_graph(self, tx: InstructionTranslator, fn_vt: VariableTracker, fn_args_vt: Sequence[VariableTracker], kwargs: dict[str, VariableTracker], body_gmod: GraphModule, attr_name: str) -> str:
        ...
    


