"""
This type stub file was generated by pyright.
"""

import collections
import torch
import torch.fx
from collections.abc import Sequence
from typing import Any, Literal, Optional, TYPE_CHECKING
from .base import VariableTracker
from .constant import ConstantVariable
from .functions import UserFunctionVariable
from .iter import IteratorVariable
from torch._dynamo.codegen import PyCodegen
from torch._dynamo.symbolic_convert import InstructionTranslator

"""
Variable tracking implementations for list-like data structures in Dynamo.

This module provides specialized variable tracking for various collection types:
- Lists and list subclasses (including torch.nn.ModuleList, ParameterList)
- Tuples and named tuples
- Ranges and slices
- Collections.deque
- torch.Size with special proxy handling

The implementations support both mutable and immutable collections, iteration,
and common sequence operations. Each collection type has a dedicated Variable
class that handles its unique behaviors while integrating with Dynamo's
variable tracking system.
"""
if TYPE_CHECKING:
    ...
class BaseListVariable(VariableTracker):
    @staticmethod
    def cls_for_instance(obj: Any) -> type[BaseListVariable]:
        ...
    
    @staticmethod
    def cls_for(obj: Any) -> type:
        ...
    
    def __init__(self, items: list[VariableTracker], **kwargs: Any) -> None:
        ...
    
    def modified(self, items: list[VariableTracker], **kwargs: Any) -> BaseListVariable:
        ...
    
    @property
    def value(self) -> Any:
        ...
    
    def debug_repr_helper(self, prefix: str, suffix: str) -> str:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def as_proxy(self) -> Any:
        ...
    
    def getitem_const(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker:
        ...
    
    def unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def sq_length(self, tx: InstructionTranslator) -> VariableTracker:
        """Sequence length for lists, tuples, and range objects."""
        ...
    
    def call_tree_map_branch(self, tx: InstructionTranslator, tree_map_fn: UserFunctionVariable, map_fn: VariableTracker, rest: Sequence[VariableTracker], tree_map_kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_tree_map_with_path_branch(self, tx: InstructionTranslator, tree_map_fn: UserFunctionVariable, map_fn: VariableTracker, rest: Sequence[VariableTracker], tree_map_kwargs: dict[str, VariableTracker], keypath: tuple[Any, ...]) -> VariableTracker:
        ...
    
    def mp_subscript_impl(self, tx: InstructionTranslator, key: VariableTracker) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class RangeVariable(BaseListVariable):
    _cpython_type = ...
    def __init__(self, items: Sequence[VariableTracker], **kwargs: Any) -> None:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    def python_type(self) -> type:
        ...
    
    def start(self) -> Any:
        ...
    
    def stop(self) -> Any:
        ...
    
    def step(self) -> Any:
        ...
    
    def range_length(self) -> int:
        ...
    
    def apply_index(self, tx: InstructionTranslator, index: int) -> VariableTracker:
        ...
    
    def apply_slice(self, slice: slice) -> RangeVariable:
        ...
    
    def as_python_constant(self) -> range:
        ...
    
    def getitem_const(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker:
        ...
    
    def as_proxy(self) -> range:
        ...
    
    def unpack_var_sequence(self, tx: Optional[InstructionTranslator] = ...) -> list[VariableTracker]:
        ...
    
    def sq_length(self, tx: InstructionTranslator) -> VariableTracker:
        """Sequence length for range objects."""
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def range_equals(self, other: RangeVariable) -> bool:
        ...
    
    def range_count(self, x: VariableTracker) -> int:
        ...
    
    def mp_subscript_impl(self, tx: InstructionTranslator, key: VariableTracker) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def is_python_hashable(self) -> Literal[True]:
        ...
    
    def get_python_hash(self) -> int:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    


class CommonListMethodsVariable(BaseListVariable):
    """
    Implement methods common to List and other List-like things
    """
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class ListVariable(CommonListMethodsVariable):
    _cpython_type = ...
    _has_instance_dict = ...
    def python_type(self) -> type:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def is_python_hashable(self) -> bool:
        ...
    


class DequeVariable(CommonListMethodsVariable):
    _cpython_type = ...
    def __init__(self, items: list[VariableTracker], maxlen: VariableTracker | None = ..., **kwargs: Any) -> None:
        ...
    
    def python_type(self) -> type:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    def as_python_constant(self) -> collections.deque[Any]:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    


class TupleVariable(BaseListVariable):
    _cpython_type = ...
    def python_type(self) -> type[tuple]:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def is_python_hashable(self) -> bool:
        ...
    
    def get_python_hash(self) -> int:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    


class SizeVariable(TupleVariable):
    """torch.Size(...)"""
    _cpython_type = torch.Size
    _nonvar_fields = ...
    def __init__(self, items: list[VariableTracker], proxy: torch.fx.Proxy | None = ..., **kwargs: Any) -> None:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    def python_type(self) -> type:
        ...
    
    def as_proxy(self) -> Any:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def numel(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def mp_subscript_impl(self, tx: InstructionTranslator, key: VariableTracker) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def get_item_dyn(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    


class SliceVariable(VariableTracker):
    _cpython_type = ...
    def __init__(self, items: Sequence[VariableTracker], tx: Optional[InstructionTranslator] = ..., **kwargs: Any) -> None:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    def as_proxy(self) -> slice:
        ...
    
    def python_type(self) -> type:
        ...
    
    def as_python_constant(self) -> slice:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    


class ListIteratorVariable(IteratorVariable):
    _cpython_type = ...
    _nonvar_fields = ...
    def __init__(self, items: list[VariableTracker], index: int = ..., **kwargs: Any) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def next_variable(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def python_type(self) -> type:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def has_unpack_var_sequence(self, tx: InstructionTranslator) -> bool:
        ...
    
    def unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def force_unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


class TupleIteratorVariable(ListIteratorVariable):
    _cpython_type = ...


class RangeIteratorVariable(IteratorVariable):
    _cpython_type = ...
    _nonvar_fields = ...
    def __init__(self, start: int, stop: int, step: int, len_: int, **kwargs: Any) -> None:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def next_variable(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def python_type(self) -> type:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


