"""
This type stub file was generated by pyright.
"""

import collections
import functools
import traceback
from collections.abc import Callable, Sequence
from typing import Any, Literal, TYPE_CHECKING, Union
from torch._guards import Source
from .. import variables
from ..source import DictGetItemSource, TypeSource
from .base import MutationType, VariableTracker
from .dicts import ConstDictVariable, DunderDictVariable
from .hashable import HashableTracker
from .sets import SetVariable
from torch._dynamo.codegen import PyCodegen
from torch._dynamo.side_effects import SideEffects
from torch._dynamo.symbolic_convert import InstructionTranslator
from torch._dynamo.variables.constant import ConstantVariable
from .lists import ListVariable, TupleVariable

"""
This module contains variable classes for handling user-defined objects in Dynamo's tracing system.

The key classes are:
- UserDefinedVariable: Base class for representing custom Python objects
- UserDefinedClassVariable: Handles Python class objects/types
- UserDefinedObjectVariable: Fallback class for instance objects, with support for method calls,
  attribute access, and other Python object behaviors.
- Specialized subclasses for common patterns:
  - UserDefinedDictVariable: For dict subclasses
  - UserDefinedSetVariable: For set subclasses
  - UserDefinedTupleVariable: For tuple subclasses
  - UserDefinedExceptionObjectVariable: For exception subclasses
  - FrozenDataClassVariable: Special handling of frozen dataclasses
  - MutableMappingVariable: For collections.abc.MutableMapping subclasses

Dynamo specializes to VariableTracker subclasses like FrozenDataClassVariable if available; if no
subclass qualifies, it falls back to UserDefinedObjectVariable.

These classes help Dynamo track and handle arbitrary Python objects during tracing,
maintaining proper semantics while enabling optimizations where possible.
"""
if TYPE_CHECKING:
    ...
def is_standard_setattr(val: object) -> bool:
    ...

def is_standard_delattr(val: object) -> bool:
    ...

def is_forbidden_context_manager(ctx: object) -> bool:
    ...

def is_cython_function(obj: object) -> bool:
    ...

def is_pydantic_dataclass_cls(value: object) -> bool:
    ...

KNOWN_DATA_DESCRIPTOR_TYPES: frozenset[type] = ...
def is_data_descriptor(obj: object) -> bool:
    """Return True if *obj* is a data descriptor (has __get__ and (__set__ or __delete__))."""
    ...

class UserDefinedVariable(VariableTracker):
    value: object
    ...


class UserDefinedClassVariable(UserDefinedVariable):
    value: type[object]
    def __init__(self, value: type[object], **kwargs: Any) -> None:
        ...
    
    def as_python_constant(self) -> type[object]:
        ...
    
    def as_proxy(self) -> object:
        ...
    
    def __repr__(self) -> str:
        ...
    
    @staticmethod
    @functools.cache
    def supported_c_new_functions() -> set[Any]:
        ...
    
    @staticmethod
    def is_supported_new_method(value: object) -> bool:
        ...
    
    def can_constant_fold_through(self) -> bool:
        ...
    
    def lookup_cls_mro_attr(self, name: str) -> object:
        """Walk cls.__mro__ only (not the metaclass chain) to find *name*."""
        ...
    
    def lookup_metaclass_attr(self, name: str) -> object:
        """Walk type(cls).__mro__ (the metaclass chain) to find *name*."""
        ...
    
    def bool_impl(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def resolve_meta_data_descriptor(self, tx: InstructionTranslator, name: str, meta_attr: object, source: Source | None) -> VariableTracker:
        """Handle data descriptors from the metaclass MRO (type.__dict__ slots)."""
        ...
    
    def resolve_cls_descriptor(self, tx: InstructionTranslator, name: str, cls_attr: object, source: Source | None) -> VariableTracker:
        """Handle descriptors found in cls.__mro__."""
        ...
    
    def resolve_cls_plain_attr(self, tx: InstructionTranslator, name: str, cls_attr: object, source: Source | None) -> VariableTracker:
        """Handle non-descriptor attributes from cls.__mro__."""
        ...
    
    def invoke_cls_descriptor_get(self, tx: InstructionTranslator, name: str, descriptor: object, source: Source | None) -> VariableTracker:
        """Trace a class-MRO descriptor's __get__(None, cls) call."""
        ...
    
    def len_impl(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def sq_length(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def mp_length(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def is_standard_new(self) -> bool:
        """Check for __new__ being overridden"""
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def const_getattr(self, tx: InstructionTranslator, name: str) -> Any:
        ...
    
    def is_python_hashable(self) -> Literal[True]:
        ...
    
    def get_python_hash(self) -> int:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    
    def get_real_python_backed_value(self) -> object:
        ...
    


class UserDefinedExceptionClassVariable(UserDefinedClassVariable):
    @property
    def fn(self) -> type[object]:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class RemovableHandleClass:
    ...


def call_random_fn(tx: InstructionTranslator, fn: Callable[..., Any], args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
    ...

class UserDefinedObjectVariable(UserDefinedVariable):
    """
    Mostly objects of defined type.  Catch-all for something where we only know the type.
    """
    _base_vt: VariableTracker | None = ...
    _base_methods: set[Any] | None = ...
    _nonvar_fields = ...
    def __init__(self, value: object, *, value_type: type | None = ..., cls_source: TypeSource | None = ..., base_cls_vt: VariableTracker | None = ..., init_args: Sequence[VariableTracker] | None = ..., **kwargs: Any) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def get_dict_vt(self, tx: InstructionTranslator) -> DunderDictVariable:
        ...
    
    def is_base_vt_modified(self, side_effects: SideEffects) -> bool:
        ...
    
    def python_type(self) -> type:
        ...
    
    def get_real_python_backed_value(self) -> object:
        ...
    
    def as_python_constant(self) -> object:
        ...
    
    def as_proxy(self) -> object:
        ...
    
    def guard_as_python_constant(self) -> object:
        ...
    
    def bool_impl(self, tx: InstructionTranslator) -> VariableTracker | None:
        ...
    
    def nb_index_impl(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def nb_int_impl(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def nb_float_impl(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def torch_function_check(self) -> None:
        ...
    
    def get_torch_fn(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def call_torch_function(self, tx: InstructionTranslator, fn: VariableTracker, types: TupleVariable, args: Sequence[Any], kwargs: dict[str, Any]) -> VariableTracker:
        ...
    
    def mp_subscript_impl(self, tx: InstructionTranslator, key: VariableTracker) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[Any], kwargs: dict[str, Any]) -> VariableTracker:
        ...
    
    def len_impl(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def sq_length(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def mp_length(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def method_setattr_standard(self, tx: InstructionTranslator, name: VariableTracker, value: VariableTracker, directly_update_dict: bool = ...) -> VariableTracker:
        ...
    
    def needs_slow_setattr(self) -> bool:
        ...
    
    def unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def has_force_unpack_var_sequence(self, tx: InstructionTranslator) -> bool:
        ...
    
    def force_unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def next_variable(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def is_supported_random(self) -> bool:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def lookup_class_mro_attr(self, name: str) -> object:
        """Walk type(obj).__mro__ to find *name* in the class hierarchy.

        This only searches the class chain (type(obj).__mro__), NOT the
        metaclass chain (type(type(obj)).__mro__).  The distinction matters
        because inspect.getattr_static conflates both chains — it can return
        metaclass descriptors (e.g. type.__dict__['__annotations__'], a
        getset_descriptor) when the attribute doesn't exist on the class MRO.
        Walking cls.__mro__ directly avoids that leak.
        """
        ...
    
    def should_skip_descriptor_setter(self, attr_name: str) -> bool:
        ...
    
    def try_get_descritor_and_setter_py_func(self, attr_name: str) -> tuple[object, object] | None:
        ...
    
    def has_key_in_generic_dict(self, tx: InstructionTranslator, key: str) -> bool:
        ...
    
    def get_source_by_walking_mro(self, tx: InstructionTranslator, name: str) -> DictGetItemSource:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def resolve_data_descriptor(self, tx: InstructionTranslator, name: str, type_attr: object, source: Source | None) -> VariableTracker:
        """Handle data descriptors found on the type MRO (property, _tuplegetter, etc.)."""
        ...
    
    def resolve_type_attr(self, tx: InstructionTranslator, name: str, type_attr: object, source: Source | None) -> VariableTracker:
        """Handle non-data descriptors and plain class attributes from the type MRO."""
        ...
    
    def invoke_descriptor_get(self, tx: InstructionTranslator, name: str, descriptor: object, source: Source | None) -> VariableTracker:
        """Trace a descriptor's __get__(instance, owner) call."""
        ...
    
    def maybe_wrap_nn_module_source_for_instance(self, tx: InstructionTranslator, name: str, source: Source | None) -> Source | None:
        """Wrap source for nn.Module instance dict attribute access if needed."""
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def is_python_hashable(self) -> bool:
        ...
    
    def get_python_hash(self) -> int:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    
    def call_tree_map_branch(self, tx: InstructionTranslator, tree_map_fn: variables.functions.UserFunctionVariable, map_fn: VariableTracker, rest: collections.abc.Sequence[VariableTracker], tree_map_kwargs: dict[str, VariableTracker]) -> VariableTracker:
        """Emulate tree_map behavior for user-defined objects.

        In pytree, a type is a leaf if it is NOT in SUPPORTED_NODES.
        User-defined objects (that are not registered with register_pytree_node)
        are always treated as leaves. This works for both torch.utils._pytree
        and optree implementations.
        """
        ...
    
    def call_tree_map_with_path_branch(self, tx: InstructionTranslator, tree_map_fn: variables.functions.UserFunctionVariable, map_fn: VariableTracker, rest: collections.abc.Sequence[VariableTracker], tree_map_kwargs: dict[str, VariableTracker], keypath: tuple[Any, ...]) -> VariableTracker:
        """Emulate tree_map_with_path behavior for user-defined objects.

        Same logic as call_tree_map_branch but passes keypath to the map function.
        """
        ...
    


class FrozenDataClassVariable(UserDefinedObjectVariable):
    """Frozen dataclass variable for as_proxy/as_python_constant/hashability.

    Construction is handled by the generic polyfill path (tracing through
    the auto-generated __init__). Field values are retrieved dynamically
    via var_getattr using InstructionTranslator.current_tx().
    """
    def as_python_constant(self) -> object:
        ...
    
    def as_proxy(self) -> object:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def is_python_hashable(self) -> Literal[True]:
        ...
    
    def get_python_hash(self) -> int:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    


class SourcelessGraphModuleVariable(UserDefinedObjectVariable):
    def __init__(self, value: object, **kwargs: Any) -> None:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class UserDefinedExceptionObjectVariable(UserDefinedObjectVariable):
    def __init__(self, value: object, **kwargs: Any) -> None:
        ...
    
    @property
    def fn(self) -> Callable[..., object]:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str): # -> VariableTracker:
        ...
    
    @property
    def __context__(self) -> ConstantVariable:
        ...
    
    @property
    def args(self) -> list[VariableTracker]:
        ...
    
    def set_context(self, context: variables.ExceptionVariable) -> None:
        ...
    
    @property
    def exc_type(self) -> type[BaseException]:
        ...
    
    @property
    def python_stack(self) -> traceback.StackSummary | None:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    @python_stack.setter
    def python_stack(self, value: traceback.StackSummary) -> None:
        ...
    


class InspectVariable(UserDefinedObjectVariable):
    """Handles inspect.Signature and inspect.Parameter objects.

    Short-circuits property accesses to avoid tracing property getters,
    redirecting them to the underlying private attributes directly.
    """
    _PROPERTY_REDIRECTS: dict[type, dict[str, str]] = ...
    @staticmethod
    def is_matching_object(obj: object) -> bool:
        ...
    
    @staticmethod
    def is_matching_class(obj: object) -> bool:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    


class KeyedJaggedTensorVariable(UserDefinedObjectVariable):
    @staticmethod
    def is_matching_object(obj: object) -> bool:
        ...
    
    def __init__(self, value: object, **kwargs: Any) -> None:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    


_CONSTANT_BASE_TYPES = ...
_constant_base_methods: dict[type, set[Any]] = ...
class UserDefinedConstantVariable(UserDefinedObjectVariable):
    """
    Represents user-defined objects that subclass immutable constant types
    (int, float, str).

    Uses a ConstantVariable as _base_vt for the underlying constant value.
    """
    def __init__(self, value: Any, **kwargs: Any) -> None:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def as_proxy(self) -> object:
        ...
    


class IntWrapperVariable(UserDefinedObjectVariable):
    @staticmethod
    def is_matching_object(obj: object) -> bool:
        ...
    


class RemovableHandleVariable(VariableTracker):
    REMOVED = ...
    def __init__(self, mutation_type: MutationType | None = ..., idx: int | None = ..., **kwargs: Any) -> None:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def python_type(self) -> type[object]:
        ...
    


class UserDefinedDictVariable(UserDefinedObjectVariable):
    """
    Represents user defined objects that are subclasses of dict/OrderedDict.

    Internally, it uses a ConstDictVariable to represent the dict part of the
    variable tracker. For everything else, it falls back to
    UserDefinedObjectVariable.
    """
    def __init__(self, value: object, dict_vt: ConstDictVariable | None = ..., **kwargs: Any) -> None:
        ...
    
    def sq_length(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def mp_subscript_impl(self, tx: InstructionTranslator, key: VariableTracker) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class UserDefinedSetVariable(UserDefinedObjectVariable):
    """
    Represents user defined objects that are subclasses of set.

    Internally, it uses a SetVariable to represent the set part of the
    variable tracker. For everything else, it falls back to
    UserDefinedObjectVariable.
    """
    def __init__(self, value: object, set_vt: SetVariable | None = ..., **kwargs: Any) -> None:
        ...
    
    def as_python_constant(self) -> object:
        ...
    
    @property
    def set_items(self) -> set[Any]:
        ...
    
    @property
    def items(self) -> dict[HashableTracker, VariableTracker]:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    


class UserDefinedListVariable(UserDefinedObjectVariable):
    """
    Represents user defined objects that are subclasses of lists.

    Internally, it uses a ListVariable to represent the list part of the
    variable tracker. For everything else, it falls back to
    UserDefinedObjectVariable.
    """
    def __init__(self, value: object, list_vt: Union[ListVariable, None] = ..., **kwargs: Any) -> None:
        ...
    


class UserDefinedTupleVariable(UserDefinedObjectVariable):
    """
    Represents user defined objects that are subclasses of tuple.

    Internally, it uses a TupleVariable to represent the tuple part of the
    variable tracker. For everything else, it falls back to
    UserDefinedObjectVariable.

    NamedTupleVariable and StructSequenceVariable are subclasses that handle
    namedtuples and structseqs (torch.return_types.*) respectively.
    """
    _nonvar_fields = ...
    @staticmethod
    def get_vt_cls(cls: type) -> type[UserDefinedTupleVariable]:
        ...
    
    def __init__(self, value, tuple_vt=..., init_args=..., **kwargs) -> None:
        ...
    
    @property
    def items(self) -> list[VariableTracker]:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def get_construct_fn(self) -> Callable[..., Any]:
        ...
    
    def call_tree_map_branch(self, tx: InstructionTranslator, tree_map_fn: variables.functions.UserFunctionVariable, map_fn: VariableTracker, rest: collections.abc.Sequence[VariableTracker], tree_map_kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_tree_map_with_path_branch(self, tx: InstructionTranslator, tree_map_fn: variables.functions.UserFunctionVariable, map_fn: VariableTracker, rest: collections.abc.Sequence[VariableTracker], tree_map_kwargs: dict[str, VariableTracker], keypath: tuple[Any, ...]) -> VariableTracker:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    


class NamedTupleVariable(UserDefinedTupleVariable):
    """Represents Python namedtuples (created via collections.namedtuple).

    Namedtuples use _tuplegetter descriptors for field access and
    Type(*args) / Type._make(iterable) for construction.
    """
    def resolve_data_descriptor(self, tx: InstructionTranslator, name: str, type_attr: object, source: Source | None) -> VariableTracker:
        ...
    
    def get_construct_fn(self) -> Callable[..., Any]:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def as_proxy(self) -> Any:
        ...
    


class StructSequenceVariable(UserDefinedTupleVariable):
    """Represents C-implemented PyStructSequence types (torch.return_types.*).

    Structseqs use Type(iterable) calling convention and reject tuple.__new__.
    """
    def resolve_data_descriptor(self, tx: InstructionTranslator, name: str, type_attr: object, source: Source | None) -> VariableTracker:
        ...
    
    def get_construct_fn(self) -> Callable[..., Any]:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def as_proxy(self) -> Any:
        ...
    


class MutableMappingVariable(UserDefinedObjectVariable):
    def __init__(self, value: object, **kwargs: Any) -> None:
        ...
    
    def method_setattr_standard(self, tx: InstructionTranslator, name: VariableTracker, value: VariableTracker, directly_update_dict: bool = ...) -> VariableTracker:
        """Override to handle property setters on MutableMapping subclasses.

        This is needed because property.__set__ is a slot wrapper (C function),
        not a Python function, so the base class's try_get_descritor_and_setter_py_func
        returns None for properties. But property.fset IS a Python function we can trace.

        Without this, property setters on newly created MutableMapping objects fail
        when accessing nested objects (which haven't been initialized yet on the
        example value). By tracing the fset, we capture the setter logic in the graph
        instead of running it on uninitialized example objects.

        TODO(compiler): This fix is scoped to MutableMapping only because tracing
        property setters on ALL UserDefinedObjectVariable can cause failures when
        the fset calls untraceable C++ functions (e.g., pybind functions). Ideally,
        this should be extended to all user-defined classes with a graceful fallback
        when tracing the fset hits an untraceable function.
        See: https://github.com/pytorch/pytorch/issues/172000
        """
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def mp_length(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    


class RandomVariable(UserDefinedObjectVariable):
    ...


