"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from cutlass_api.arguments import GemmArguments
from cutlass_api.artifact import CompiledArtifact
from cutlass_api.metadata import KernelMetadata
from cutlass_api.providers.cutedsl.kernel import CuteDslKernel
from ..dense_blockscaled_gemm_persistent import Sm100BlockScaledPersistentDenseGemmKernel as BlockScaledGemmKernelImpl

"""Kernel wrapper for dense_blockscaled_gemm_persistent vendored template."""
log = ...
class VendoredDenseBlockScaledGemmKernel(CuteDslKernel):
    """Wrapper for vendored dense blockscaled GEMM template for SM100 GPUs."""
    def __init__(self, metadata: KernelMetadata) -> None:
        ...
    
    def compile(self, args: GemmArguments, cc: int | None = ...) -> CompiledArtifact:
        ...
    
    def get_workspace_size(self, args: GemmArguments) -> int:
        ...
    
    @staticmethod
    def generate_kernels(metadata_filter: Callable[[KernelMetadata], bool], epilogue_args=..., cc: int | None = ...) -> list[VendoredDenseBlockScaledGemmKernel]:
        ...
    


if BlockScaledGemmKernelImpl is not None:
    ...
