"""
This type stub file was generated by pyright.
"""

import torch
from typing import Any
from torch.distributed.tensor._op_schema import OpSchema, OutputSharding, RuntimeSchemaInfo
from torch.distributed.tensor._ops.single_dim_strategy import _ShardingPlaceholder, register_single_dim_strategy
from torch.distributed.tensor._ops.utils import register_prop_rule
from torch.distributed.tensor.placement_types import Placement

aten = ...
@register_prop_rule(aten.convolution.default)
def convolution_rules(op_schema: OpSchema) -> OutputSharding:
    ...

@register_prop_rule(aten.convolution_backward.default)
def convolution_backward_rules(op_schema: OpSchema) -> OutputSharding:
    ...

@register_single_dim_strategy([aten.convolution.default], schema_info=RuntimeSchemaInfo(2))
def convolution_single_dim_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

@register_single_dim_strategy([aten.convolution_backward.default], schema_info=RuntimeSchemaInfo(3))
def convolution_backward_single_dim_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder | None]]:
    ...

