"""
This type stub file was generated by pyright.
"""

import torch
from dataclasses import dataclass
from enum import Enum
from typing import Any
from torch.distributed.tensor._op_schema import OpSchema, OpStrategy, RuntimeSchemaInfo, TupleStrategy
from torch.distributed.tensor._ops.single_dim_strategy import _ShardingPlaceholder, register_single_dim_strategy
from torch.distributed.tensor._ops.utils import register_op_strategy
from torch.distributed.tensor.placement_types import Partial, Placement

aten = ...
prims = ...
class Reduction(Enum):
    NONE = ...
    MEAN = ...
    SUM = ...


@dataclass(frozen=True)
class NormReduction:
    norm_type: int | float
    ...


ReductionOpType = NormReduction | str
@dataclass(frozen=True)
class _NormPartial(Partial):
    """
    This placement is used for partial p-norm (p not in {inf, -inf, 0}).

    For p-norms, the p-norm over n elements computes (sum_i x_i^p)^(1/p).
    For example, consider 2 ranks, a (4,) tensor sharded on dim-0, and 2-norm:
        Rank 0: [t1, t2] | Rank 1: [t3, t4]
    After computing 2-norm per gradient (partial placement):
        Rank 0: [sqrt(t1^2 + t2^2)] | Rank 1: [sqrt(t3^2 + t4^2)]
    Converting from partial to replicate wants to ultimately get:
        Rank 0/1: [sqrt(t1^2 + t2^2 + t3^2 + t4^2)]
    This is achieved by: x^p -> allreduce sum -> x^(1/p).
    """
    norm_type: int | float = ...
    def __init__(self, norm_type: int | float = ...) -> None:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


def replicate_reduction_dims(placements: tuple[Placement, ...], reduction_dims: list[int]) -> tuple[Placement, ...]:
    ...

def map_placements_after_reduction(placements: tuple[Placement, ...], reduction_dims: list[int], reduction_dims_map: list[int], reduction_op: ReductionOpType) -> tuple[Placement, ...]:
    """
    Map each placement based on the output shape after reduction.
    """
    ...

def get_placement_from_reduction_op(reduction_op: ReductionOpType) -> Placement:
    ...

def common_reduction_strategy(input_strategy: OpStrategy, reduce_dims: list[int], keep_dim: bool = ..., reduction_linear: bool = ..., reduction_op: ReductionOpType = ...) -> OpStrategy:
    """
    reduction_linear means that the reduction `f` follows this rule:
        f([f(a), f(b)]) = f([a, b])

    reduction linear should be super set of linearity.
    """
    ...

LINEAR_REDUCTION_OP_MAP = ...
ARGMAX_ARGMIN_OPS = ...
@register_op_strategy(list(LINEAR_REDUCTION_OP_MAP.keys()), schema_info=RuntimeSchemaInfo(1))
def linear_reduction_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_single_dim_strategy([aten.max.dim, aten.min.dim], schema_info=RuntimeSchemaInfo(1))
def max_min_dim_single_dim_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

@register_op_strategy(list(ARGMAX_ARGMIN_OPS.keys()), schema_info=RuntimeSchemaInfo(1))
def argmax_argmin_strategy(op_schema: OpSchema) -> OpStrategy:
    """
    Strategy for argmax/argmin. These return indices, not values, so they cannot
    use P(max/min) output placements. The indices are local to each shard and
    cannot be meaningfully combined across ranks with a max/min reduction.
    Force redistribution on reduction dimensions by using reduction_linear=False.
    """
    ...

@register_op_strategy([aten.cumsum.default, aten.cumprod.default, aten.logcumsumexp.default], schema_info=RuntimeSchemaInfo(1))
def scan_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_op_strategy([aten.median.default, aten.nanmedian.default], schema_info=RuntimeSchemaInfo(1))
def global_median_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_single_dim_strategy([aten.median.dim, aten.nanmedian.dim, aten.mode.default], schema_info=RuntimeSchemaInfo(1))
def dim_reduction_with_indices_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

@register_single_dim_strategy([aten.kthvalue.default], schema_info=RuntimeSchemaInfo(2))
def kthvalue_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

@register_op_strategy([aten.cummax.default, aten.cummin.default], schema_info=RuntimeSchemaInfo(1))
def cummax_cummin_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_op_strategy([aten.std.correction, aten.std.correction_out, aten.var.correction, aten.var.correction_out, aten.var_mean.correction, aten.var_mean.correction_out, prims.var.default], schema_info=RuntimeSchemaInfo(1, ["keepdim"]))
def std_var_reduction_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_op_strategy([aten.linalg_vector_norm.default, aten.norm.Scalar], schema_info=RuntimeSchemaInfo(1))
def vector_norm_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_op_strategy([aten._foreach_norm.Scalar], schema_info=RuntimeSchemaInfo(1, needs_pytree=True))
def foreach_norm_strategy(op_schema: OpSchema) -> TupleStrategy:
    ...

@register_op_strategy([aten.linalg__powsum.default], schema_info=RuntimeSchemaInfo(1))
def powsum_strategy(op_schema: OpSchema) -> OpStrategy:
    """
    Strategy for linalg__powsum: computes sum(|x|^ord) without the final root.
    Output is always reducible with Partial("sum").
    """
    ...

@register_op_strategy([aten._foreach_powsum.Scalar], schema_info=RuntimeSchemaInfo(1, needs_pytree=True))
def foreach_powsum_strategy(op_schema: OpSchema) -> TupleStrategy:
    """
    Strategy for _foreach_powsum: computes sum(|x|^ord) for each tensor.
    Output is always reducible with Partial("sum").
    """
    ...

@register_op_strategy([aten._foreach_max.default], schema_info=RuntimeSchemaInfo(1, needs_pytree=True))
def foreach_max_strategy(op_schema: OpSchema) -> TupleStrategy:
    """
    Strategy for _foreach_max, which reduces each tensor in a list to its maximum value.
    """
    ...

@register_op_strategy([aten._linalg_svd.default, aten.linalg_qr.default, aten.diagonal_copy.default, aten.diag_embed.default, aten.diag.default, aten.diagonal.default, aten.tril.default, aten.triu.default, aten._linalg_eigh.default], schema_info=RuntimeSchemaInfo(1))
def linalg_replicate_strategy(op_schema: OpSchema) -> OpStrategy:
    """
    Since we do not have a simple way to compute some linear algebra operations
    like SVD or QR decomposition, always fall back to replicate.
    """
    ...

POOL_SPATIAL_RANK: dict[torch._ops.OpOverload, int] = ...
AVG_POOL_OPS = ...
MAX_POOL_OPS = ...
@register_op_strategy(AVG_POOL_OPS + MAX_POOL_OPS, schema_info=RuntimeSchemaInfo(1))
def pooling_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_op_strategy([aten._log_softmax.default, aten._softmax.default, aten._safe_softmax.default], schema_info=RuntimeSchemaInfo(1))
def softmax_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_op_strategy([aten._log_softmax_backward_data.default, aten._softmax_backward_data.default], schema_info=RuntimeSchemaInfo(2))
def softmax_backward_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_op_strategy([aten.nll_loss_forward.default, aten.nll_loss2d_forward.default], schema_info=RuntimeSchemaInfo(3))
def nll_loss_forward_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_op_strategy([aten.nll_loss_backward.default, aten.nll_loss2d_backward.default], schema_info=RuntimeSchemaInfo(4))
def nll_loss_backward_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_single_dim_strategy([aten.native_layer_norm.default], schema_info=RuntimeSchemaInfo(1))
def layer_norm_single_dim_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

@register_single_dim_strategy([aten._fused_rms_norm.default], schema_info=RuntimeSchemaInfo(1))
def rms_norm_single_dim_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

@register_single_dim_strategy([aten.native_layer_norm_backward.default], schema_info=RuntimeSchemaInfo(2))
def layer_norm_bwd_single_dim_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder | None]]:
    ...

@register_single_dim_strategy([aten._fused_rms_norm_backward.default], schema_info=RuntimeSchemaInfo(2))
def rms_norm_bwd_single_dim_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder | None]]:
    ...

def sort_strategy(op_schema: OpSchema, sort_dim: int) -> OpStrategy:
    ...

@register_op_strategy([aten.topk.default], schema_info=RuntimeSchemaInfo(2))
def topk_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_op_strategy(aten.sort.default, schema_info=RuntimeSchemaInfo(1))
def sort_default_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_op_strategy(aten.sort.stable, schema_info=RuntimeSchemaInfo(1, static_kwargkey=["dim", "descending", "stable"]))
def sort_stable_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_op_strategy([aten.histc.default], schema_info=RuntimeSchemaInfo(2))
def histc_strategy(op_schema: OpSchema) -> OpStrategy:
    ...

@register_op_strategy([aten.logsumexp.default], schema_info=RuntimeSchemaInfo(static_argnum=1, static_kwargkey=["keepdim"]))
def logsumexp_strategy(op_schema: OpSchema) -> OpStrategy:
    """Implements the sharding propagation strategy for logsumexp."""
    ...

_LINALG_NUM_PLACEMENTS = ...
@register_single_dim_strategy([aten.cholesky.default, aten.cholesky_inverse.default, aten.linalg_matrix_exp.default, aten.cholesky_solve.default, aten.linalg_householder_product.default, aten.linalg_solve_triangular.default, aten.linalg_ldl_solve.default, aten.linalg_lu_solve.default, aten.ormqr.default, aten.geqrf.default, aten.linalg_cholesky_ex.default, aten.linalg_eig.default, aten.linalg_inv_ex.default, aten.triangular_solve.default, aten._linalg_det.default, aten.linalg_ldl_factor_ex.default, aten.linalg_lu.default, aten.linalg_lu_factor_ex.default, aten.lu_unpack.default, aten._linalg_slogdet.default, aten._linalg_solve_ex.default, aten._linalg_check_errors.default], schema_info=RuntimeSchemaInfo(1))
def linalg_batch_dim_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

@register_single_dim_strategy([aten.linalg_pinv.atol_rtol_tensor], schema_info=RuntimeSchemaInfo(1))
def linalg_pinv_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

@register_single_dim_strategy([aten.linalg_cross.default], schema_info=RuntimeSchemaInfo(1))
def linalg_cross_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

@register_single_dim_strategy([aten.upsample_nearest1d.default, aten.upsample_nearest2d.default, aten.upsample_nearest3d.default, aten._upsample_nearest_exact1d.default, aten._upsample_nearest_exact2d.default, aten._upsample_nearest_exact3d.default, aten._upsample_bilinear2d_aa.default, aten.upsample_bicubic2d.default, aten.upsample_bilinear2d.default, aten.upsample_linear1d.default, aten.upsample_trilinear3d.default], schema_info=RuntimeSchemaInfo(1))
def interp_upsample_1out_1in_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

@register_single_dim_strategy([aten.max_unpool2d.default, aten.max_unpool3d.default, aten._adaptive_avg_pool2d_backward.default], schema_info=RuntimeSchemaInfo(1))
def interp_pool_1out_2in_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

@register_single_dim_strategy([aten.max_pool2d_with_indices_backward.default], schema_info=RuntimeSchemaInfo(1))
def pool_backward_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

@register_single_dim_strategy([aten.grid_sampler_2d.default, aten.grid_sampler_3d.default], schema_info=RuntimeSchemaInfo(1))
def grid_sampler_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

@register_single_dim_strategy([aten.grid_sampler_2d_backward.default, aten.grid_sampler_3d_backward.default], schema_info=RuntimeSchemaInfo(1))
def grid_sampler_backward_strategy(op: torch._ops.OpOverload, args_schema: tuple[Any, ...], kwargs_schema: dict[str, Any]) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

