"""
This type stub file was generated by pyright.
"""

import torch
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass
from typing import NamedTuple
from torch import Tensor
from torch._prims_common import DimsType
from torch.distributed.tensor._op_schema import RuntimeSchemaInfo
from torch.distributed.tensor._ops.single_dim_strategy import register_single_dim_strategy
from torch.distributed.tensor.placement_types import Placement

aten = ...
Shape = tuple[int, ...]
class ClaimedDim(NamedTuple):
    """An (input_dim, output_dim) pair claimed by a mesh dim's _StridedShard rewrite."""
    input_dim: int
    output_dim: int
    ...


@dataclass
class DimSpec:
    """Specifies how an output dimension maps to an input dimension."""
    def inputs(self) -> Iterable[DimSpec]:
        ...
    


DimMap = tuple[DimSpec, ...]
@dataclass
class Singleton(DimSpec):
    """Output dimension is a singleton."""
    ...


@dataclass(eq=False)
class InputDim(DimSpec):
    """Output dimension maps directly to an input dimension."""
    input_dim: int
    def __eq__(self, other: object) -> bool:
        """Raises TypeError for non-DimSpec comparisons to catch accidental
        ``shard.dim == input_dim`` bugs where ``.input_dim`` was intended."""
        ...
    
    def __hash__(self) -> int:
        ...
    


@dataclass
class Broadcast(DimSpec):
    """Output is the broadcast of a singleton input dimension."""
    dim: DimSpec
    dim_size: int
    @classmethod
    def new(cls, dim: DimSpec, dim_size: int) -> DimSpec:
        ...
    
    def inputs(self) -> Iterable[DimSpec]:
        ...
    


@dataclass
class NewDim(DimSpec):
    """This is a new dimension created by the op."""
    size: int
    @classmethod
    def new(cls, size: int) -> DimSpec:
        ...
    


@dataclass
class Repeat(DimSpec):
    """Output dimension is the input dimension repeated n-times."""
    input_dim: DimSpec
    times: int
    @classmethod
    def new(cls, dim: DimSpec, times: int) -> DimSpec:
        ...
    
    def inputs(self) -> Iterable[DimSpec]:
        ...
    


@dataclass
class Flatten(DimSpec):
    """Flatten a set of input dimensions, ensuring right-most adjacent elements remain adjacent in the output."""
    input_dims: Sequence[DimSpec]
    @classmethod
    def new(cls, dims: Sequence[DimSpec]) -> DimSpec:
        ...
    
    def inputs(self) -> Iterable[DimSpec]:
        ...
    


@dataclass
class Split(DimSpec):
    """
    This dimension is a member of a decomposition of the input dim.

    Note that input_dim itself could be a Flattened set of input dims.
    """
    input_dim: DimSpec
    group_shape: Shape
    split_id: int
    @classmethod
    def new(cls, dim: DimSpec, group_shape: tuple[int, ...], idx: int) -> DimSpec:
        ...
    
    def inputs(self) -> Iterable[DimSpec]:
        ...
    


def dim_pad_left(ndim: int, min_dims: int) -> DimMap:
    ...

def dim_atleast_3d(ndim: int) -> DimMap:
    ...

def expand(input_shape: Shape, shape: Shape) -> DimMap:
    """Implement broadcast on multiple dimensions."""
    ...

def normalize_sizes(sizes: Shape | tuple[Shape]) -> Shape:
    ...

def dim_flatten(ndim: int, start_dim=..., end_dim=...) -> DimMap:
    ...

def dim_movedim(ndim: int, input: DimsType, destination: DimsType) -> DimMap:
    ...

def dim_repeat(ndim: int, sizes: Shape) -> DimMap:
    ...

def infer_size(total_size: int, sizes: Shape) -> Shape:
    """
    One dimension input to view may be "-1".

    Infer the size of this dimension given the total_size.
    """
    ...

def view_groups(from_size: Shape, to_size: Shape) -> DimMap:
    """
    Decompose a reshape operation into forwarding, flattening, or splitting dimensions for each output dimension.

    A view or reshape operation can be decomposed into a set of 3 types of smaller operations:
    1) Forward a dimension from input to output
    2) Flatten a set of dimensions into a single dimension
    3) Split one dimension into multiple dimensions

    view_groups identifies these operations and returns, for each output dimension, what
    is operation was performed in the input dimension. For example:

        view_groups([2, 3, 4], [2, 12]) -> (
            InputDim(0),
            Flatten((InputDim(1), InputDim(2)))
        )

    - output dimension 0 maps to input dimension 0
    - output dimension 1 maps to a flattened input dimensions 1 and 2


        view_groups([2, 3], [3, 2]) -> (
            Split(Flatten((InputDim(0), InputDim(1))), (3, 2), 0),
            Split(Flatten((InputDim(0), InputDim(1))), (3, 2), 1),
        )

    - in the above, input is flattened into a single dimension and then split
      into two separate dimensions with different sizes from the input.
    """
    ...

def dim_tile(ndim: int, dims: tuple[int, ...]) -> DimMap:
    ...

def dim_transpose(ndim: int, dim1: int, dim2: int) -> DimMap:
    ...

def dim_squeeze(shape: Shape, dim: DimsType | None = ...) -> DimMap:
    ...

def dim_unsqueeze(ndim: int, dim: int) -> DimMap:
    ...

def dim_view_as_real(shape: Shape) -> DimMap:
    ...

def dim_reduction(ndim: int, dim_or_dims: DimsType | None, keepdim: bool) -> DimMap:
    """
    General fallback for reduction ops where Partial() does not apply.

    This will cause incoming tensor to be replicated on the reducing dimensions.
    """
    ...

dim_maps: dict[Callable[..., torch.Tensor], Callable[..., DimMap]] = ...
def propagate_shape_and_sharding(input_src_placements: Sequence[Placement], global_input_shape: Shape, rule: DimMap, mesh_sizes: Shape, strict_view: bool = ...) -> tuple[Sequence[Placement], Sequence[Placement]]:
    """
    Determine input target sharding and output sharding based on
    given global tensor shape and input source sharding.

    Sharding propagation follows mapped dimensions:
    - An output dimension that maps directly to an input dimension is sharded equally
    - An output dimension that is a flattened set of input dimensions can be sharded:
      the first sharded dim stays as Shard, non-first sharded dims become _StridedShard
    - An output dimension that is a split of the input dimension can only be sharded
      if the leftmost split size is divisible by the mesh dimension
    """
    ...

class _ViewShardingPropagator:
    """Two-phase sharding propagator for view ops.

    Phase 1 — ``analyze()``:
      Walks the DimMap rule and returns:
      - ``input_tgt_placements``: input placements with unshardable dims
        demoted to Replicate.
      - ``input_to_output_tensor_dims``: maps each input tensor dim to its
        output dim(s).  Cardinality encodes the op type: 1→1 for InputDim,
        N→1 for Flatten, 1→N for Split/unflatten.

    Phase 2 — ``rewrite_output_placements()``:
      Consumes both Phase 1 outputs.  Iterates mesh dims 0..n-1, maintaining:
      - ``strided_shard_claimed_dims``: (input_dim, output_dim) pairs already assigned
        to a mesh dim by _StridedShard rewriting.
      - ``local_tensor_shapes``: global shape progressively divided by each
        mesh dim's shard size.
      For each surviving Shard/_StridedShard, looks up the output dim(s) and
      produces the final output placement.
    """
    def __init__(self, input_src_placements: Sequence[Placement], global_input_shape: Shape, rule: DimMap, mesh_sizes: Shape, strict_view: bool) -> None:
        ...
    
    def analyze(self) -> tuple[Sequence[Placement], dict[int, list[int]]]:
        """Phase 1: walk the DimMap rule, return (input_tgt_placements, input_to_output_tensor_dims)."""
        ...
    
    def rewrite_output_placements(self, input_tgt_placements: Sequence[Placement], input_to_output_tensor_dims: dict[int, list[int]]) -> list[Placement]:
        """Phase 2: consume analyze() outputs, return final output placements."""
        ...
    


def register_op_strategy_map(aten_op_overload: torch._ops.OpOverload, local_op_name: Callable[..., torch.Tensor], schema_info: RuntimeSchemaInfo | None = ..., strict_view: bool = ...) -> None:
    """
    Helper that registers strategies for view-like operators that follow a pattern:
      (1) define the way input dims are split/combined to form output dims (dim_maps)
      (2) register a strategy for the op schema that uses the dim_map as a sharding prop rule

    strict_view: if True, we will error out if the view-operation would require resharding the input.
       Currently, this should be set to 'true' for any "view" ops.
       We could diverge behavior for "reshape" ops which could perform a redistribute implicitly.
    """
    ...

@register_single_dim_strategy(aten.view_as_complex.default)
def view_as_complex_single_dim_strategy(op, args_schema, kwargs_schema): # -> list[list[Placement | _ShardingPlaceholder]]:
    ...

