"""
This type stub file was generated by pyright.
"""

import torch
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from typing import TypeAlias, TypeVar
from torch._ops import OpOverload
from torch.distributed.tensor._dtensor_spec import DTensorSpec, TensorMeta
from torch.distributed.tensor._op_schema import ArgsType, KwargsType, OpSchema, OpStrategy, RuntimeSchemaInfo, StrategyType
from torch.distributed.tensor.device_mesh import DeviceMesh
from torch.distributed.tensor.placement_types import Placement, Shard, _StridedShard

logger = ...
class _ShardingPlaceholder:
    """
    A placeholder for a sharding placement that has a specified tensor dim, but the other
    metadata (e.g. split factor if it's a StridedShard) will be filled in later.
    """
    dim: int
    def __init__(self, dim: int) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    


_StrategyTypeT = TypeVar("_StrategyTypeT", bound=StrategyType)
_PlacementT = TypeVar("_PlacementT", bound=Placement)
_ShardingPlaceholderT = TypeVar("_ShardingPlaceholderT", bound=_ShardingPlaceholder)
_SingleDimStrategyFunc: TypeAlias = Callable[[OpOverload, ArgsType, KwargsType], list[list[_PlacementT | _ShardingPlaceholderT]]]
_ExpandedSingleDimStrategyFunc: TypeAlias = Callable[[OpOverload, ArgsType, KwargsType], _StrategyTypeT]
@dataclass
class _SingleDimStrategyInfo:
    func: _SingleDimStrategyFunc
    allow_unbacked_sharding: bool | None = ...
    allow_uneven_sharding: bool = ...
    different_mesh_args: list[int] | None = ...
    def __call__(self, *args, **kwargs): # -> list[list[Any]]:
        ...
    


class _PreparedSingleDimStrategy:
    """A single-dim strategy materialized for a specific op.

    Expands a strategy function's placeholder-based rules into concrete
    placement rules by filling in the actual shard/partial placements from
    the op_schema. The result is a lookup table (strategy_lookup) that maps
    input placements to output placements for one mesh dimension.

    Provides try_propagate() for matching a multi-dim placement tuple against
    the per-dim rules, and exposes allowed_sharding_per_input /
    allowed_partial_per_input for graph search neighbor generation.
    """
    strategy_lookup: dict[tuple[Placement | None, ...], tuple[Placement | None, ...]]
    expanded_strategies: list[list[Placement | None]]
    num_outputs: int
    num_inputs: int
    output_metas: tuple[TensorMeta | None, ...]
    allowed_sharding_per_input: dict[int, set[Shard | _StridedShard]]
    allowed_partial_per_input: dict[int, set[Placement]]
    allow_unbacked_sharding: bool | None
    allow_uneven_sharding: bool
    def __init__(self, strategy_fn: _SingleDimStrategyInfo | Callable[[OpOverload, ArgsType, KwargsType], list[list[Placement | _ShardingPlaceholder]],], op_schema: OpSchema, output_tensor_meta: TensorMeta | Sequence[TensorMeta | None] | None, num_inputs: int | None = ...) -> None:
        ...
    
    def try_propagate(self, mesh: DeviceMesh, input_placements: tuple[tuple[Placement, ...], ...], input_specs: list[DTensorSpec]) -> OpStrategy | None:
        """Try to match input placements against single-dim strategy rules on every mesh dim.

        Checks whether the given input placements independently match a rule in
        strategy_lookup on each mesh dimension, and that all inputs are shardable
        with those placements. If so, returns an OpStrategy with the matched output
        placements and zero redistribute costs.
        """
        ...
    


def register_single_dim_strategy(op: torch._ops.OpOverload | list[torch._ops.OpOverload], schema_info: RuntimeSchemaInfo | None = ..., allow_unbacked_sharding: bool | None = ..., allow_uneven_sharding: bool = ..., different_mesh_args: list[int] | None = ...) -> Callable[[_SingleDimStrategyFunc], _SingleDimStrategyFunc]:
    """
    Registers a single_dim_strategy function for the given op.

    A single_dim_strategy enumerates all the non-trivial sharding specifications for the operator over a single mesh
    dim. Since it generates the full set of valid shardings regardless of the given input placements, tensor inputs
    are represented via TensorMetas instead of OpStrategies like in op_strategy functions. TensorMeta inputs, along
    with all other op inputs (int, float, bool, etc) inform which sharding placements are valid. Single-dim strategies
    are fed into infra that expands them over multiple mesh dims and fills sharding placeholders with concrete sharding
    types.

    Single-dim-strategies should not list the trivial "all Replicate" rule, which is assumed for all ops.

    Sharding placeholders should be used to represent generic sharding rules in single_dim_strategies.  For example,
    most operators that support sharded inputs and outputs do not care how the shards are laid out globally, as long as
    they are consistent.  It is just as valid to run a matmul on (Shard(0), Replicate -> Shard(0)) as on
    (StridedShard(0), Replicate -> StridedShard(0)).  For this reason, we use a 'ShardingPlaceholder' to represent all
    generic sharding types.  Placeholders will be filled by concrete sharding types seen in runtime inputs, not all
    types known to DTensor.

    """
    ...

@dataclass(order=True)
class _PQEntry:
    """Priority queue entry for the Dijkstra search in _dijkstra_expand_single_dim_strategy_to_mesh.

    Ordered by (cost, counter) for heap comparison. The counter breaks ties
    in FIFO order so that entries with equal cost are explored in insertion
    order rather than by arbitrary tuple comparison on placements.
    """
    cost: float
    counter: int
    placements: tuple[tuple[Placement, ...], ...] = ...
    transitions: list[tuple[int, int, Placement, Placement]] = ...
    per_input_costs: tuple[float, ...] = ...
    per_input_comm_bytes_gb: tuple[float, ...] = ...


