"""
This type stub file was generated by pyright.
"""

r"""Contains definitions of the methods used by the _BaseDataLoaderIter to put fetched tensors into pinned memory.

These **needs** to be in global scope since Py2 doesn't support serializing
static methods.
"""
def pin_memory(data, device=...): # -> Tensor | str | bytes | Any | dict[Any, Tensor | Any | str | bytes | dict[Any, Tensor | Any | str | bytes | dict[Any, Any] | tuple[Any, ...] | list[Any]] | tuple[Any, ...] | list[Any]] | tuple[Any, ...] | list[Any]:
    ...

