"""
This type stub file was generated by pyright.
"""

import random
import torch
from dataclasses import dataclass
from typing import TYPE_CHECKING
from . import IS_WINDOWS
from torch.utils.data import Dataset

r"""Contains definitions of the methods used by the _BaseDataLoaderIter workers.

These **needs** to be in global scope since Py2 doesn't support serializing
static methods.
"""
if TYPE_CHECKING:
    ...
if IS_WINDOWS:
    class ManagerWatchdog:
        def __init__(self) -> None:
            ...
        
        def is_alive(self) -> bool:
            ...
        
    
    
else:
    class ManagerWatchdog:
        def __init__(self) -> None:
            ...
        
        def is_alive(self) -> bool:
            ...
        
    
    
_worker_info: WorkerInfo | None = ...
@dataclass(frozen=True, slots=True)
class WorkerInfo:
    """Information about the current DataLoader worker process or thread.

    Attributes:
        id: The current worker id (0 to num_workers - 1)
        num_workers: Total number of workers
        seed: Random seed set for this worker
        dataset: Copy of the dataset object in this worker
        rng: Optional RNG state container. Defaults to None.
        worker_method: Optional worker method ("multiprocessing" or "thread"). Defaults to "multiprocessing".
    """
    id: int
    num_workers: int
    seed: int
    dataset: Dataset
    rng: _RNG | None = ...
    worker_method: str | None = ...


def get_worker_info() -> WorkerInfo | None:
    r"""Returns the information about the current
    :class:`~torch.utils.data.DataLoader` iterator worker process.

    When called in a worker, this returns an object guaranteed to have the
    following attributes:

    * :attr:`id`: the current worker id.
    * :attr:`num_workers`: the total number of workers.
    * :attr:`seed`: the random seed set for the current worker. This value is
      determined by main process RNG and the worker id. See
      :class:`~torch.utils.data.DataLoader`'s documentation for more details.
    * :attr:`dataset`: the copy of the dataset object in **this** process. Note
      that this will be a different object in a different process than the one
      in the main process.

    When called in the main process, this returns ``None``.

    .. note::
       When used in a :attr:`worker_init_fn` passed over to
       :class:`~torch.utils.data.DataLoader`, this method can be useful to
       set up each worker process differently, for instance, using ``worker_id``
       to configure the ``dataset`` object to only read a specific fraction of a
       sharded dataset, or use ``seed`` to seed other libraries used in dataset
       code.
    """
    ...

@dataclass(frozen=True)
class _IterableDatasetStopIteration:
    worker_id: int
    ...


@dataclass(frozen=True)
class _ResumeIteration:
    seed: int | None = ...


@dataclass(frozen=True, slots=True)
class _RNG:
    """Container for thread-local random number generator state.

    Used by thread workers to maintain separate RNG state per worker thread
    to avoid race conditions.

    Attributes:
        random_generator: Python random.Random generator for this thread
        torch_generator: PyTorch Generator for this thread
        numpy_generator: NumPy Generator for this thread (None if numpy not available)
    """
    random_generator: random.Random
    torch_generator: torch.Generator
    numpy_generator: object | None = ...


