"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum
from torch.distributed.tensor import DeviceMesh, Shard
from ._fsdp_api import DataParallelMeshDims

@dataclass
class DataParallelMeshInfo:
    mesh: DeviceMesh
    shard_mesh_dim: int | None = ...
    replicate_mesh_dim: int | None = ...
    dp_mesh_dims: DataParallelMeshDims | None = ...
    spmd_mesh: DeviceMesh | None = ...
    is_spmd_mesh: bool = ...
    def __post_init__(self): # -> None:
        ...
    


@dataclass
class FSDPMeshInfo(DataParallelMeshInfo):
    def __post_init__(self): # -> None:
        ...
    


@dataclass
class DDPMeshInfo(DataParallelMeshInfo):
    def __post_init__(self): # -> None:
        ...
    


@dataclass
class HSDPMeshInfo(FSDPMeshInfo, DDPMeshInfo):
    def __post_init__(self): # -> None:
        ...
    


class TrainingState(Enum):
    """Describes the training state of one FSDP state / parameter group."""
    FORWARD = ...
    PRE_BACKWARD = ...
    POST_BACKWARD = ...
    IDLE = ...


def is_bw() -> bool:
    ...

@dataclass
class ShardPlacementResult:
    placement: Shard | None
    mesh_info: FSDPMeshInfo
    ...


ShardPlacementFnResult = Shard | ShardPlacementResult | None
def resolve_shard_placement(result: ShardPlacementFnResult, default_mesh_info: FSDPMeshInfo) -> ShardPlacementResult:
    """Resolve the shard_placement_fn result to a ShardPlacementResult.

    Handles different input types and applies defaults:
    - None: Use default sharding (Shard(0)) on default mesh
    - Shard: Use specified shard dimension on default mesh
    - ShardPlacementResult: Use as-is

    Args:
        result: The return value from shard_placement_fn, or None if no fn provided.
        default_mesh_info: The default FSDPMeshInfo to use if not specified.

    Returns:
        A ShardPlacementResult with placement and mesh_info.
    """
    ...

