"""
This type stub file was generated by pyright.
"""

import torch.fx as fx
from torch.utils._ordered_set import OrderedSet

log = ...
class AugmentedGraphHelper:
    """
    Graph helper that augments the original graph with additional
    dependencies and uses, plus tracks node equivalences for coalescing.

    TODO: if this becomes too large of compile time, consider binding
    graphcycles.cc
    """
    def __init__(self, graph: fx.Graph, node_ancestors: dict[fx.Node, OrderedSet[fx.Node]] | None = ...) -> None:
        ...
    
    def add_extra_dep(self, *, n: fx.Node, dep: fx.Node) -> None:
        """Add extra dependency: node depends on dep."""
        ...
    
    def remove_extra_dep(self, *, n: fx.Node, dep: fx.Node) -> None:
        ...
    
    def merge_to_set(self, existing_node: fx.Node, new_node: fx.Node) -> None:
        """
        Merge new_node into existing_node's set. The new node must be a singleton set.
        """
        ...
    
    def unmerge_node(self, node: fx.Node) -> None:
        """Remove a node from its merge set, making it singleton."""
        ...
    
    def get_merged_deps(self, node: fx.Node) -> OrderedSet[fx.Node]:
        """
        Get all dependencies of a node considering merges and extra deps.
        Combines:
        1. Direct deps (all_input_nodes) of node and its merge equivalents
        2. Extra deps of node and its merge equivalents
        """
        ...
    
    def has_cycle(self) -> bool:
        ...
    
    def has_path(self, source: fx.Node, target: fx.Node) -> bool:
        """Check if there's a path from source to target."""
        ...
    
    def transfer_erased_node_deps(self, erased_to_new: dict[fx.Node, fx.Node | None]) -> None:
        """
        Transfer all extra dependencies from erased nodes to their replacements, handling
        cross-dependencies between erased nodes correctly.

        Skips deps where both endpoints resolve to replacement nodes from the
        same erasure batch — these are intra-bucket deps that would create
        cycles (e.g. new_start <-> new_wait within the same bucket).
        """
        ...
    
    def remove_erased_extra_deps(self) -> None:
        """Remove extra deps referencing erased nodes."""
        ...
    
    def check_and_maybe_autofix_cyclic_extra_deps(self, *, autofix: bool = ...) -> None:
        """Check for and optionally remove extra deps that create cycles.

        Args:
            autofix: If True, silently remove cyclic deps.  If False (default),
                raise an error so the root cause gets investigated.
        """
        ...
    
    def get_all_extra_deps(self) -> dict[fx.Node, OrderedSet[fx.Node]]:
        """
        Get all extra dependencies in a format suitable for topological sort.
        Returns a copy to avoid external modifications.
        """
        ...
    


