"""
This type stub file was generated by pyright.
"""

import sympy
from collections.abc import Callable, Iterable, Sequence
from typing import Any
from sympy import Expr
from torch import SymInt
from torch.fx.experimental.symbolic_shapes import IterateExprs, ShapeEnv
from torch.utils._ordered_set import OrderedSet
from torch.utils._sympy.value_ranges import ValueRanges
from .utils import VarRanges
from .virtualized import V

log = ...
_GEMM_TEMPLATE_SYMBOL_NAMES = ...
def statically_known_true(shape_env: ShapeEnv, expr: sympy.Basic | bool, axioms: tuple[sympy.Expr] | None = ..., var_to_range: tuple[tuple[sympy.Symbol, ValueRanges[Any]]] | None = ...) -> bool:
    ...

class SizeVarAllocator:
    """
    A class that manages symbolic size variables and their relationships.

    This class works with the ShapeEnv to handle symbolic shape expressions,
    simplify them, and provide utilities for guarding, checking, and evaluating
    symbolic expressions. It also manages precomputed replacements and stride
    calculations for tensor operations.
    """
    def __init__(self, shape_env=...) -> None:
        ...
    
    def simplify(self, expr: Expr):
        ...
    
    def make_simplify_with_ranges_cache(self) -> Callable[[Expr, VarRanges], Expr]:
        """
        self._simplify_with_ranges() can be expensive, cache its results
        """
        ...
    
    def make_simplify_loops_cache(self): # -> Callable[..., tuple[list[Any], Callable[..., list[Any]], Callable[..., list[Any]]] | Any]:
        """
        self._simplify_with_ranges() can be expensive, cache its results
        """
        ...
    
    def statically_known_true(self, expr: sympy.Basic | bool) -> bool:
        """
        Returns true if an expression is always true (symbolically or via guards),
        false otherwise. Never add guards, or throw data dependent errors.
        """
        ...
    
    def statically_known_equals(self, left: Expr | int, right: Expr | int) -> bool:
        """
        Returns a bool indicating if it is sound to optimize as if left and right are equal.
        """
        ...
    
    def statically_known_list_equals(self, left: Sequence[Expr], right: Sequence[Expr]) -> bool:
        """
        Returns a bool indicating if it is sound to optimize as if left and right lists are equal.
        """
        ...
    
    def statically_known_leq(self, left: Expr, right: Expr | int) -> bool:
        """
        Returns a bool indicating if it is sound to optimize as if left is less than or equal to right.
        """
        ...
    
    def statically_known_geq(self, left: Expr, right: Expr | int) -> bool:
        """
        Returns a bool indicating if it is sound to optimize as if left is greater than or equal to right.
        """
        ...
    
    def statically_known_lt(self, left: Expr, right: Expr | int) -> bool:
        """
        Returns a bool indicating if it is sound to optimize as if left is less than right.
        """
        ...
    
    def statically_known_gt(self, left: Expr, right: Expr | int) -> bool:
        """
        Returns a bool indicating if it is sound to optimize as if left is greater than right.
        """
        ...
    
    def statically_known_multiple_of(self, numerator: Expr, denominator: Expr | int) -> bool:
        """
        Return a bool indicating if it is sound to optimize for the numerator being a multiple of the denominator.
        """
        ...
    
    def statically_known_power_of_2(self, expr: Expr) -> bool:
        """
        Returns a bool indicating if x is known to be a power of 2.
        """
        ...
    
    def expect_true(self, expr: Expr) -> bool:
        """
        Use it when you already know that expr is true or should be true and want to
        ensure that guards/runtime assertions are in place to ensure this in compiled
        function. Unlike check, this WON'T raise an error if expr isn't actually true.
        check Note [expect_true].
        """
        ...
    
    def check(self, expr: Expr) -> None:
        """
        Use it when you already know that expr is true or should be true and want to
        ensure that guards/runtime assertions are in place to ensure this in compiled
        function. Unlike expect_true, this WILL raise an error if expr isn't actually true.
        check Note [expect_true].
        """
        ...
    
    def check_equals(self, left: Expr, right: Expr) -> None:
        """
        check(sympy.Eq(left, right)).

        """
        ...
    
    def check_equals_and_simplify(self, left: Expr, right: Expr) -> Expr:
        """
        check(sympy.Eq(left, right)) and returns left after applying
        inv_precomputed_replacements.
        """
        ...
    
    def check_leq(self, left: Expr, right: Expr) -> None:
        ...
    
    def check_lt(self, left: Expr, right: Expr) -> None:
        ...
    
    def guard_or_false(self, left): # -> Basic | bool:
        ...
    
    def guard_or_true(self, left): # -> Basic | bool:
        ...
    
    def evaluate_expr(self, left: Expr | sympy.logic.boolalg.Boolean, size_oblivious: bool = ..., fallback_value: bool | None = ...) -> bool:
        ...
    
    def is_size_one_or_false(self, size: Expr) -> bool:
        """Return True if size equals 1.

        Unbacked symbolic sizes return False without introducing a guard.
        """
        ...
    
    def evaluate_min(self, left: Expr, right: Expr) -> Expr:
        """Return the smaller of left and right, and guard on that choice."""
        ...
    
    def evaluate_max(self, left: Expr, right: Expr) -> Expr:
        """Return the larger of left and right, and guard on that choice."""
        ...
    
    def guard_int(self, expr: Expr | int) -> int:
        """
        Similar to guard_int in symbolic_shapes.py, except this function works with SymPy
        expressions instead of SymNodes. It extracts the value represented by expr from shapeEnv
        and specialize the compiled graph on it. Raises an error if the result cannot be
        determined due to unhinted or unbacked symbols.
        """
        ...
    
    def guard_int_seq(self, left: Sequence[Expr | int]) -> list[int]:
        """
        Apply guard_int on a sequence of inputs.
        """
        ...
    
    def remove_precomputed_replacements(self, expr: Expr) -> Expr:
        ...
    
    def replace_backed_symbols_with_hints(self, expr: Expr | int) -> Expr | int:
        """
        Replace all backed symbols in an expression with their concrete hint values.

        This function substitutes backed symbolic variables with their known concrete
        values from the shape environment, while leaving unbacked symbols (data-dependent
        values) untouched. Not recommended to be used except as last resort!
        was added for existing usages compatibility.
        """
        ...
    
    def to_symint_or_int(self, expr: Expr | int) -> SymInt | int:
        """Convert a sympy expression to SymInt, or return int as is."""
        ...
    
    def to_symints_or_ints(self, exprs: Sequence[Expr | int]) -> list[SymInt | int]:
        """Convert a sequence of sympy expressions to SymInts, or return ints as is."""
        ...
    
    def guarding_hint_or_throw(self, expr: Expr | int) -> int:
        """
        Return a concrete integer hint for an expression that is safe to use for guarding.

        This method evaluates the expression using only backed-symbols hints. Unlike
        optimization_hint(), this method does NOT use heuristics or fallback values
        for unbacked symbols.

        Use this method when you need a hint value that will be used for guarding decision.

        Args:
            expr: A sympy expression or integer to evaluate.

        Returns:
            The concrete integer value of the expression based on backed symbol hints.

        Raises:
            GuardOnDataDependentSymNode: If the expression contains unbacked symbols
            (data-dependent values) that cannot be resolved to concrete values.

        See Also:
            optimization_hint: For cases where fallback/heuristic values are acceptable
                for unbacked symbols.
        """
        ...
    
    def optimization_hint(self, expr: Expr | int, fallback: int | None = ...) -> int:
        """
        Return a concrete integer hint for an expression.

        This function should be used for non-guarding based optimizations. If you
        want a hint that you can guard on, use the guarding_hint API instead.

        This function will hint unbacked symbols using user provided optimization
        hints. If not provided, fallback will be used along with some heuristics
        that try to maximize consistency with the shape environment.

        Special cases:
        - Complex numbers (containing sympy.I): raises an error since tensor
          dimensions cannot be complex.
        - Infinity (int_oo, sympy.oo): returns sys.maxsize.
        - NaN (sympy.nan): returns the fallback value.
        """
        ...
    
    def optimization_hints(self, exprs: Iterable[Expr | int], fallback: int | None = ...) -> tuple[int, ...]:
        """
        Like optimization_hint but for a sequence of expressions.
        Returns a tuple of concrete integer hints.
        """
        ...
    
    def all_unbacked_explicitly_hinted(self, exprs: IterateExprs) -> bool:
        """
        Return True if every unbacked symbol in *exprs* has an explicit
        user-provided hint in var_to_hint_override.  If there are no
        unbacked symbols at all, returns True (vacuously).
        *exprs* can be a single expression or any iterable accepted by
        free_unbacked_symbols (list, tuple, etc.).
        """
        ...
    
    def optimization_hint_with_override(self, expr: Expr | int, hint_override: int | None) -> int:
        r"""Return a concrete integer hint for an expression, with optional override.
        This is used in dynamic dispatch scenarios where callers may want to
        provide a specific hint value rather than computing one from the expression.
        The resolution order is:
        1. If ``expr`` simplifies to a static integer, return that value
           (``hint_override`` is ignored for static shapes).
        2. If ``expr`` is dynamic and ``hint_override`` is not ``None``,
           return ``hint_override``.
        3. Otherwise, compute a hint via :meth:`optimization_hint`
        Args:
            expr (Expr or int): The expression to get a hint for.
            hint_override (int, optional): If provided and ``expr`` is dynamic,
                this value is returned instead of computing a hint.
        Returns:
            int: A concrete integer hint for the expression.
        """
        ...
    
    def optimization_hints_with_override(self, exprs: Iterable[Expr | int], hint_override: int | None) -> tuple[int, ...]:
        """
        Like optimization_hint_with_override but for a sequence of expressions.
        Returns a tuple of concrete integer hints.
        """
        ...
    
    def guarding_hints_or_throw(self, exprs: Iterable[Expr | int]) -> tuple[int, ...]:
        ...
    
    def make_stride_vars_cache(self): # -> Callable[..., list[Expr]]:
        ...
    
    def offset_var(self, index: Expr, vars: Sequence[sympy.Symbol]) -> Expr:
        """Extract offset part of an indexing expression"""
        ...
    
    def stride_hints(self, index: Expr, vars: Sequence[sympy.Symbol], support_vars: Sequence[sympy.Symbol] | None = ...) -> list[int]:
        ...
    
    def stride_order(self, index: Expr, vars: list[sympy.Symbol]) -> list[int]:
        ...
    
    def lookup_precomputed_size(self, expr: Expr) -> Expr:
        ...
    
    def free_symbols(self) -> OrderedSet[sympy.Symbol]:
        ...
    
    def combine_modular_indexing_pairs(self, index: sympy.Expr) -> sympy.Expr:
        """
        A pair of special ModularIndexing can be combined.

        E.g. ModularIndexing(ModularIndexing(x, 1, a), 1, b)
        We can simplify this to ModuleIndexing(x, 1, b), if
        1. x is non negative integer
        2. a and b are positive integers
        3. a is a multiple of b.
        """
        ...
    
    def expand_floor_div(self, index: sympy.Expr) -> bool | tuple[sympy.Expr, sympy.Expr]:
        """
        Expand the FloorDiv to the entire expression so that the expression may
        be simplified.

        E.g., for a 2D contiguous tensor with shape [a, 2 * b], and index variables
        x1, x2, index expression 'x1 * 2b + x2' can be easily combined.
        But index expression 'x1 * b + x2 // 2' can not.
        By expanding the FloorDiv to the entire expression, we get
        '(x1 * 2b + x2) // 2'. This transformation allows us to merge loops
        for the numerator!

        Return false if this optimization can be applied;
        Return the new expression and the denominator otherwise.
        The original expression will be equivalent to 'new_expression // denominator'
        """
        ...
    


def join_dimensions(expr: Expr) -> Expr:
    ...

class SimplifyIndexing(V.WrapperHandler):
    """
    A wrapper around .virtualize.ops that uses var range information to
    simplify ModularIndexing/FloorDiv.
    """
    def __init__(self, inner, var_ranges: VarRanges) -> None:
        ...
    
    def load(self, name: str, index: sympy.Expr): # -> Any:
        ...
    
    def store(self, name, index, value, mode=...): # -> None:
        ...
    
    def store_reduction(self, name, index, value): # -> None:
        ...
    
    def index_expr(self, index, dtype): # -> Any:
        ...
    
    def check_bounds(self, index, size, lower, upper): # -> None:
        ...
    


