"""
This type stub file was generated by pyright.
"""

import functools

"""Stream utilities for Inductor codegen."""
__all__ = ["DEFAULT_STREAM", "DEFAULT_STREAM_IDX", "STREAM_NAME_TEMPLATE", "get_raw_stream_name", "get_stream_name"]
@functools.lru_cache
def get_stream_name(stream_idx: int) -> str:
    """Generate CUDA Stream name from stream index number.

    Args:
        stream_idx: Non-negative index number. 0 refers to the default stream, others refer to side
            streams.
    """
    ...

def get_raw_stream_name(device_idx: int) -> str:
    """Generate variable name for a raw stream handle on the given device."""
    ...

