"""
This type stub file was generated by pyright.
"""

import functools

@functools.cache
def has_jax_package() -> bool:
    """Check if JAX is installed."""
    ...

@functools.cache
def has_pallas_package() -> bool:
    """Check if Pallas (JAX experimental) is available."""
    ...

@functools.cache
def get_jax_version(fallback: tuple[int, int, int] = ...) -> tuple[int, int, int]:
    """Get JAX version as (major, minor, patch) tuple."""
    ...

@functools.cache
def has_jax_cuda_backend() -> bool:
    """Check if JAX has CUDA backend support with SM90+ (required by Mosaic GPU)."""
    ...

@functools.cache
def has_jax_tpu_backend() -> bool:
    """Check if JAX has TPU backend support."""
    ...

@functools.cache
def has_torch_tpu() -> bool:
    """Check if torch_tpu is installed and available."""
    ...

@functools.cache
def has_cpu_pallas() -> bool:
    """Checks for a full Pallas-on-CPU environment."""
    ...

@functools.cache
def has_cuda_pallas() -> bool:
    """Checks for a full Pallas-on-CUDA environment."""
    ...

@functools.cache
def has_tpu_pallas() -> bool:
    """Checks for a full Pallas-on-TPU environment."""
    ...

@functools.cache
def has_pallas() -> bool:
    """
    Check if Pallas backend is fully available for use.

    Requirements:
    - JAX package installed
    - Pallas (jax.experimental.pallas) available
    - A compatible backend (CUDA or TPU) is available in both PyTorch and JAX.
    """
    ...

