"""
This type stub file was generated by pyright.
"""

from torch.utils._debug_mode._calls import _AnnotateCall, _DebugCall, _OpCall, _OutputPlacementCall, _RedistributeCall, _TritonKernelCall, _get_call_name
from torch.utils._debug_mode._mode import DebugInterpreter, DebugMode, get_active_debug_mode
from torch.utils._debug_mode._utils import TensorIdTracker, _stringify_shape, hash_tensor_fn, norm_hash_fn

"""
DebugMode: a debugging TorchDispatchMode that intercepts and logs runtime calls.

See torch.utils._debug_mode._mode for the full implementation and docstring.
"""
__all__ = ["DebugMode", "get_active_debug_mode"]
