"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from torch.utils._debug_mode._utils import TensorIdTracker
from torch._dynamo.device_interface import DeviceInterface

"""
Call record classes for DebugMode: _DebugCall and its subclasses.
"""
if TYPE_CHECKING:
    ...
class _DebugCall:
    """Base class for tracking operator calls in DebugMode"""
    def __init__(self, call_depth: int, record: dict[str, Any] | None = ..., log: dict[str, Any] | None = ..., stack: bool = ...) -> None:
        ...
    
    def stringify_args(self, attributes: list[str], tensor_memo: TensorIdTracker | None = ...) -> None:
        """
        To reduce memory consumption, this method stringifies args/kwargs, stores the result, and deletes original args/kwargs.
        """
        ...
    
    def stringify_output(self, output: Any, attributes: list[str], tensor_memo: TensorIdTracker | None = ...) -> None:
        """Store stringified version of call output in self.output_str"""
        ...
    
    def render(self, attributes: list[str]) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    


class _OpCall(_DebugCall):
    """Normal operator call"""
    def __init__(self, op, args: tuple, kwargs: dict, call_depth: int, stack: bool = ...) -> None:
        ...
    
    def stringify_args(self, attributes: list[str], tensor_memo: TensorIdTracker | None = ...) -> None:
        ...
    
    def render(self, attributes: list[str]) -> str:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    


class _RedistributeCall(_DebugCall):
    def __init__(self, arg, src_placement, dst_placement, transform_info_str, call_depth, stack=..., is_explicit=...) -> None:
        ...
    
    def stringify_args(self, attributes: list[str], tensor_memo: TensorIdTracker | None = ...) -> None:
        ...
    
    def render(self, attributes: list[str]) -> str:
        ...
    
    def __iter__(self): # -> Generator[list[Any] | int | dict[Any, Any] | Literal['redistribute_input'], Any, None]:
        ...
    


class _OutputPlacementCall(_DebugCall):
    """Records output placement for a DTensor op."""
    def __init__(self, placements_str: str, call_depth: int) -> None:
        ...
    
    def stringify_args(self, attributes: list[str], tensor_memo: TensorIdTracker | None = ...) -> None:
        ...
    
    def render(self, attributes: list[str]) -> str:
        ...
    


class _TritonKernelCall(_DebugCall):
    """Triton kernel call from Inductor"""
    def __init__(self, kernel_name: str, kwargs: dict[str, Any], call_depth: int) -> None:
        ...
    
    def stringify_args(self, attributes: list[str], tensor_memo: TensorIdTracker | None = ...) -> None:
        ...
    
    def render(self, attributes: list[str]) -> str:
        ...
    
    def finalize(self, device_interface: DeviceInterface): # -> None:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    


class _AnnotateCall(_DebugCall):
    """Custom annotation call"""
    def __init__(self, tag: Any, header: str, call_depth: int, stack: bool = ...) -> None:
        ...
    
    def render(self, attributes: list[str]) -> str:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        ...
    


