"""
This type stub file was generated by pyright.
"""

import contextlib
import torch
from collections.abc import Callable
from typing import Any, TYPE_CHECKING
from torch.utils._debug_mode._calls import _TritonKernelCall
from torch.utils._python_dispatch import TorchDispatchMode

"""
DebugMode is a debugging TorchDispatchMode that intercepts and logs runtime calls
to a hierarchical string dump. It logs real tensor, DTensor, and optionally FakeTensor
operations, with some additional handling for DTensor internals.

An example dump from an eager mode DTensor matmul:

    torch.mm(dt$0: f32[8, 8]| S(0), dt$1: f32[8, 32]| S(0))  ->  dt$6: f32[8, 32]| S(0)
      aten::mm(dt$0: f32[8, 8]| S(0), dt$1: f32[8, 32]| S(0))
        redistribute_input(1, S(0) -> R)
          redistribute_input(t$2: f32[1, 32], trace: S(0)->R)
            _c10d_functional::all_gather_into_tensor(t$2: f32[1, 32], 8, 0)  ->  t$3: f32[8, 32]
            _c10d_functional::wait_tensor(t$3: f32[8, 32])  ->  t$3: f32[8, 32]
        aten::mm(t$4: f32[1, 8], t$3: f32[8, 32])  ->  t$5: f32[1, 32]

This mode runs "under" compile, which means it hides itself during compilation, and is re-enabled
at runtime, and DebugMode-related operations won't show up in the compiled region.
DebugMode also provides some visibility into non-torch-dispatch calls (e.g. DTensor redistribute calls,
inductor-generated triton kernels), but requires special handling for these, since dispatch modes
can't intercept them by default.

The mode also provides some extensions for custom debugging (e.g. adding custom dispatch call hooks
via dispatch_hooks), or numerics debugging (e.g. tensor hashing for bitwise equivalence/closeness,
via log_tensor_hashes). These decorators allow annotating string dumps with additional per-call information,
for any region of runtime code.

Usage::

    with DebugMode() as debug_mode:
        result = some_pytorch_operation(tensor_input)
    print(debug_mode.debug_string())
"""
if TYPE_CHECKING:
    ...
log = ...
_ACTIVE_DEBUG_MODE_COUNT = ...
_annotate_decorated = ...
class DebugInterpreter(torch.fx.Interpreter):
    """
    Interpreter class for running aot_eager compiled regions when DebugMode is active,
    instead of using the compiled code. This gives us access to fx.Node metadata to decorate
    and contextualize DebugMode logs (e.g. nn_module_stack, stack_trace, compiled region boundaries).

    Note: this is currently only enabled with DebugMode(run_compile_with_interpreter=True).
    """
    def __init__(self, module, backend) -> None:
        ...
    
    def run_node(self, n: torch.fx.Node) -> Any:
        ...
    
    def run(self, *args, **kwargs): # -> Any:
        ...
    


class DebugMode(TorchDispatchMode):
    def __init__(self, *, record_torchfunction=..., record_faketensor=..., record_realtensor=..., record_tensor_attributes=..., record_nn_module=..., store_original_args=..., record_stack_trace=..., record_output=..., record_ids=..., record_profiler_context=..., record_localtensor=..., run_compile_with_interpreter=...) -> None:
        ...
    
    def reset(self) -> None:
        ...
    
    @classmethod
    def ignore_compile_internals(cls) -> bool:
        ...
    
    def __torch_function__(self, func, types, args=..., kwargs=...):
        ...
    
    def __torch_dispatch__(self, func, types, args=..., kwargs=...): # -> NotImplementedType | None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, *args): # -> None:
        ...
    
    @contextlib.contextmanager
    def set_fx_stack_trace(self, stack_trace): # -> Generator[None, Any, None]:
        ...
    
    def module_tracker_setup(self) -> None:
        ...
    
    @contextlib.contextmanager
    def record_redistribute_calls(self, arg, src_placement, dst_placement, transform_info_str: str | None = ..., is_explicit: bool = ...): # -> Generator[None, Any, None]:
        ...
    
    def record_output_placements(self, output_spec) -> None:
        """Record output placements for a DTensor op as a separate line."""
        ...
    
    def record_triton_kernel(self, kernel_name: str, kwargs: dict[str, Any]) -> _TritonKernelCall:
        ...
    
    def debug_string(self, show_stack_trace: bool | None = ...) -> str:
        """
        show_stack_trace: option to display one-line stack trace summaries above groups
                        of operations (similar to gm.print_readable() style).
                        Requires record_stack_trace=True.
                        if None, uses self.record_stack_trace, otherwise overrides it.
        """
        ...
    
    @staticmethod
    @contextlib.contextmanager
    def dispatch_hooks(record_hook: Callable | None = ..., log_hook: Callable | None = ..., pre_log_hook: Callable | None = ...): # -> Generator[None, Any, None]:
        """
        Allows installing post-hooks on arguments to intercepted __torch_dispatch__ calls;
        hook signatures are expected as (func, types, args, kwargs, result),
        i.e. __torch_dispatch__ args + return value.

        Logging hook outputs are stored in call.log and annotate calls in debug_string(),
        while recording hook outputs are just stored in call.record.
        For now hooks are expected to return dictionaries.

        pre_log_hook signature is (func, types, args, kwargs, call) and is executed before
        the operation. It allows capturing state before in-place mutations.
        """
        ...
    
    @staticmethod
    @contextlib.contextmanager
    def record_outputs(): # -> Generator[None, Any, None]:
        """
        Hook for storing cloned output tensors in .record["output"].
        """
        ...
    
    @staticmethod
    @contextlib.contextmanager
    def log_tensor_hashes(hash_fn: Callable | str | list[str] = ..., hash_inputs: bool = ...): # -> Generator[None, Any, None]:
        """
        Installs hook for tensor hash logging.

        hash_fn: One of:
            - Custom-defined hash function
            - String: one of ("norm", "hash_tensor")
                - "norm": uses norm_hash_fn; basically tensor's L1 norm
                - "hash_tensor": uses torch.hash_tensor (XOR sum reduction)
            - List of strings: returns tuple of hashes from above options
        hash_inputs: if True, also hashes tensors in (args, kwargs), storing them in "input_hash".
        Input hashes are captured before the operation executes, so they reflect the state before
        any in-place mutations.
        """
        ...
    
    @property
    def logs(self): # -> list[Any]:
        ...
    
    @staticmethod
    def check_hash_mismatches(logs1: list, logs2: list, compare_inputs: bool = ...) -> list[dict]:
        """
        Compares tensor hashes between two DebugMode runs, for checking run-to-run numerical divergence.

        This first validates the two log sequences have identical structure (same operations, input shapes/dtypes, etc.),
        then compares tensor hash values, and returns a list of call outputs where mismatches were found.
        Expects input logs to have been run with log_tensor_hashes, and looks for hashes in .log["hash"] & .log["input_hash"]
        (or .post_hashes & .pre_hashes for triton kernels).

        note: skips checking log pairs where hashes aren't present, but will raise if present in one & not the other.

        Args:
            logs1: logs from the first DebugMode run (from debug_mode.logs)
            logs2: logs from the second DebugMode run
            compare_inputs: If True, also compare input tensor hashes (default: only output checking)

        Returns:
            List of dictionaries describing hash mismatches. Each dict contains:
                - call_type: "torch op" or "triton kernel"
                - call: Operator/kernel name
                - arg_name: For triton kernels, the argument name; None for torch ops
                - pytree_path: For torch ops, the pytree path to the differing tensor; None for kernels
                - hash1: Hash value from the first run
                - hash2: Hash value from the second run
                - rel_diff: Relative difference between hash values
                - is_input_hash: True if this is an input hash, False for output hash

        Raises:
            ValueError: If logs have different lengths, call types, operator names, or call depths

        Usage::

            # Run model first time
            with DebugMode() as debug_mode, DebugMode.log_tensor_hashes():
                model(x)
                logs1 = debug_mode.logs

            # Run again, in exactly the same way
            with DebugMode() as debug_mode, DebugMode.log_tensor_hashes():
                model(x)
                logs2 = debug_mode.logs

            mismatches = DebugMode.check_hash_mismatches(logs1, logs2)
            for m in mismatches:
                print(f"{m['call']}: hash diff {m['rel_diff']:.2e}")
        """
        ...
    


def get_active_debug_mode() -> DebugMode | None:
    ...

