"""
This type stub file was generated by pyright.
"""

import torch
from collections.abc import Callable
from typing import TYPE_CHECKING

"""
Utility functions for DebugMode: tensor formatting, hashing, stack traces, and hook runners.
"""
if TYPE_CHECKING:
    ...
REDISTRIBUTE_FUNC = ...
_IN_INDUCTOR_BENCHMARK: bool = ...
_RECORD_TRITON_OUTPUTS: bool = ...
_TRITON_OUTPUT_HASH_FN: Callable | None = ...
_TRITON_INPUT_HASH_FN: Callable | None = ...
_DISPATCH_RECORD_HOOKS: list[Callable] = ...
_DISPATCH_LOG_HOOKS: list[Callable] = ...
_DISPATCH_PRE_LOG_HOOKS: list[Callable] = ...
class TensorIdTracker:
    def __init__(self) -> None:
        ...
    


def norm_hash_fn(t: torch.Tensor, use_scalar: bool = ...) -> torch.Tensor | float:
    """
    from Observer. Computes a hash for a tensor by converting it to float (if needed), making it contiguous,
    replacing NaN/inf values with fixed numbers, and then computing the L1 norm in float64 or complex128.
    This is used to generate a deterministic summary value for tensor comparison.
    """
    ...

def hash_tensor_fn(t: torch.Tensor, use_scalar: bool = ...) -> torch.Tensor | int:
    """
    wrapper over torch.hash_tensor
    """
    ...

