"""
This type stub file was generated by pyright.
"""

import torch
from typing import Any
from torch._logging import LazyString

def lazy_format_graph_code(name: str, gm: torch.fx.GraphModule, maybe_id: int | None = ..., **kwargs: Any) -> LazyString:
    """
    Returns a LazyString that formats the graph code.
    """
    ...

def first_call_function_nn_module_stack(graph: torch.fx.Graph) -> dict[str, Any] | None:
    """
    Returns the nn_module_stack of the first call_function node.
    """
    ...

def get_node_context(node: torch.fx.Node, num_nodes: int = ...) -> str:
    """
    Returns a string of the last num_nodes nodes in the graph.
    """
    ...

