"""
This type stub file was generated by pyright.
"""

import functools
from typing import Any
from torch._inductor.utils import clear_on_fresh_cache

log = ...
CONFIG_PREFIX: str = ...
def get_config_request_key(arch: str, toolkit_version: str, instantiation_level: str) -> str:
    """
    Return a key for the full ops, based on cutlass key, arch, toolkit version, instantiation level, and serialization.py file hash.
    """
    ...

@clear_on_fresh_cache
@functools.cache
def maybe_fetch_ops(device_type: str) -> list[Any] | None:
    """
    Fetch ops from databases.
    """
    ...

