"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from torch.fx.graph_module import GraphModule

if TYPE_CHECKING:
    ...
def inline_invoke_subgraph(gm: GraphModule) -> GraphModule:
    """Inline all invoke_subgraph HOPs, producing a flat FX graph.

    This is useful when downstream compilers (like vllm-compile) don't support
    HOPs or prefer a flat graph, but we still want the Dynamo tracing-time
    benefits of auto-caching (trace once, stamp out cached calls).
    """
    ...

