"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from torch._subclasses import FakeTensorMode
from torch.fx.experimental.symbolic_shapes import ShapeEnv
from .schemas import AOTConfig, FakifiedFlatArgs

if TYPE_CHECKING:
    ...
static_inputs_log = ...
def process_inputs(flat_args: list[Any], aot_config: AOTConfig, fake_mode: FakeTensorMode, shape_env: ShapeEnv | None, ignore_shape_env: bool = ...) -> tuple[FakifiedFlatArgs, list[int]]:
    """Convert real tensor inputs into fake tensors for AOT autograd tracing.

    Called at compile time (not runtime) to produce the fake inputs that AOT
    autograd traces through. Each real tensor is converted to a FakeTensor
    via ``fake_mode.from_tensor``, preserving shape, dtype, device, and
    symbolic shape information from the ShapeEnv. Non-tensor inputs (ints,
    SymInts, ScriptObjects) are converted or passed through as appropriate.

    Tensor subclass inputs (DTensor, etc.) are fakified recursively by
    walking their ``__tensor_flatten__`` attrs. AsyncCollectiveTensors are
    resolved via ``trigger_wait()`` before fakification so they don't appear
    in the traced metadata (see below).

    Called from ``aot_function``, ``aot_module_simplified``, and
    ``aot_export_module`` — anywhere AOT autograd needs fake inputs before
    graph capture.

    Returns:
        A tuple of (fakified_args, act_input_indices) where act_input_indices
        records which positions held AsyncCollectiveTensors. These indices are
        stored on ViewAndMutationMeta so that the runtime wrapper can emit
        direct trigger_wait() calls on those positions.
    """
    ...

def construct_fake_mode(flat_args: list[Any], aot_config: AOTConfig) -> tuple[FakeTensorMode, ShapeEnv | None]:
    ...

