"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from .schemas import PlainTensorMeta, SubclassCreationMeta

"""
Codegen for AOTDispatchSubclassWrapper.

Generates a Python function that replaces the data-driven
runtime_unwrap_tensor_subclasses / wrap_tensor_subclasses loop with
a straight-line function where all metadata (indices, attr names,
subclass types, symint positions) is baked in at compile time.
"""
log = ...
class _CodegenState:
    """Accumulates lines of generated source and global bindings."""
    def __init__(self) -> None:
        ...
    
    def emit(self, line: str, indent: int = ...) -> None:
        ...
    
    def fresh_name(self, prefix: str) -> str:
        ...
    
    def add_global(self, name: str, value: object) -> str:
        ...
    


def codegen_backward_subclass_fns(grad_input_metas: list[PlainTensorMeta | SubclassCreationMeta] | None = ...) -> tuple[Callable[..., object], Callable[..., object] | None]:
    """Generate codegen'd unwrap and wrap functions for the backward pass.

    Returns (unwrap_fn, wrap_fn). unwrap_fn is used by the backward prologue
    to unwrap non-tangent subclass inputs (always an identity in AOT dispatch
    since the compiled forward operates on unwrapped inner tensors). wrap_fn
    is used by the backward epilogue to wrap flat grad inputs back into
    subclasses; it is None when grad_input_metas is None.
    """
    ...

def codegen_subclass_wrapper(compiled_fn: Callable[..., object], inp_metas: list[PlainTensorMeta | SubclassCreationMeta], out_metas: list[PlainTensorMeta | SubclassCreationMeta], num_fw_outs_saved_for_bw: int | None, frozen_inp_indices: frozenset[int] = ..., act_input_indices: list[int] | None = ...) -> Callable[..., object]:
    """Generate a specialized wrapper function for subclass unwrap/wrap."""
    ...

