"""
This type stub file was generated by pyright.
"""

import torch
from torch.utils._python_dispatch import TorchDispatchMode

class CUDAGraphCaptureControlFlowOpDispatchMode(TorchDispatchMode):
    @classmethod
    def ignore_compile_internals(cls) -> bool:
        ...
    
    def __init__(self) -> None:
        ...
    
    def __torch_dispatch__(self, func, types, args=..., kwargs=...):
        ...
    


class ControlFlowOpWarmupDispatchMode(TorchDispatchMode):
    """The purpose of this TodchDispatchMode is to "warm up" both sides of a torch.cond() statement.

    For data-dependent control flow code, only one side will be
    executed. Therefore, it is not safe to stream capture a
    torch.cond() statement naively, since we don't have a guarantee
    that all ops will have been "warmed up". The clever workaround is
    to use a "relaxed" stream capture whose final cuda graph we throw
    away. This works because stream capture does not actually execute
    any GPU code, and because true_fn and false_fn are both fxgraphs,
    which do not have any CPU side effects.
    """
    @classmethod
    def ignore_compile_internals(cls) -> bool:
        ...
    
    def __init__(self) -> None:
        ...
    
    def __torch_dispatch__(self, func, types, args=..., kwargs=...):
        ...
    


def if_else_node(pred: torch.Tensor, true_fn, false_fn, operands):
    ...

