"""
This type stub file was generated by pyright.
"""

import contextlib
import torch
import torch.utils._pytree as pytree
from collections.abc import Callable, Generator, Sequence
from dataclasses import dataclass
from typing import Any, NamedTuple
from torch._C import DispatchKey
from torch._higher_order_ops.utils import register_fake
from torch._library.opaque_object import OpaqueBase
from torch._ops import HigherOrderOperator
from torch.fx.experimental.proxy_tensor import ProxyTorchDispatchMode

_leaf_function_module_retriever: Callable[[int], Any] | None = ...
_makefx_module_storage: dict[int, torch.nn.Module] = ...
_makefx_next_index = ...
def store_makefx_modules(modules: list[torch.nn.Module]) -> tuple[int, ...]:
    """Store modules for the make_fx path and return their assigned indices.

    Uses negative indices to avoid collisions with Dynamo's register_user_object
    which uses non-negative indices.
    """
    ...

def reset_makefx_module_storage() -> None:
    ...

class _LeafCallable(OpaqueBase):
    def __init__(self, fn: Callable) -> None:
        ...
    
    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        ...
    


def set_leaf_function_module_retriever(retriever: Callable[[int], Any]) -> None:
    ...

class LeafModuleState(NamedTuple):
    """
    In dynamo, nn.Module arguments to leaf functions are converted to this
    pytree format (index, parameters, buffers). This structure is then
    flattened to produce the actual inputs to invoke_leaf_function.

    At runtime, the original module is reconstructed from it.
    """
    nn_module_index: int
    named_parameters: dict[str, torch.nn.Parameter]
    named_buffers: dict[str, torch.Tensor]
    ...


def convert_modules_to_states(values: Any, module_to_index: dict[int, int]) -> Any:
    """Replace nn.Module instances in a pytree with LeafModuleState objects.

    Args:
        values: A pytree of values that may contain nn.Module instances.
        module_to_index: Mapping from id(module) to its integer index.
    """
    ...

@dataclass
class GradientInfo:
    """
    We need the gradient edge to trigger the autograd engine backward.

    We need the tensor metadata (size, stride, dtype, device) to create zeros when
    gradient is None at runtime but required by the backward graph (because the graph
    is traced with fake implementation).
    """
    edge: torch.autograd.graph.GradientEdge
    size: torch.Size
    stride: tuple[int, ...]
    dtype: torch.dtype
    device: torch.device
    ...


def check_escaped_gradients(outputs: Any, inputs: Sequence[Any], requires_grad_indices: set[int]) -> None:
    """
    Check if autograd graph depends on tensors that not passed as explicit inputs.

    Controlled by torch._dynamo.config.leaf_function_check_escaped_gradients.
    """
    ...

@contextlib.contextmanager
def unflatten_args_with_modules(flat_args: tuple[Any, ...], input_spec: pytree.TreeSpec) -> Generator[tuple[list[Any] | tuple[Any, ...], dict[str, Any]], None, None]:
    ...

def flatten_args_with_modules(args_kwargs: tuple[Any, ...]) -> list[Any]:
    ...

def make_leaf_function_wrappers(real_fn: Callable[..., Any], fake_fn: Callable[..., Any], captured_out_spec: list[pytree.TreeSpec | None]) -> tuple[Callable[..., tuple[Any, ...]], Callable[..., tuple[Any, ...]]]:
    """Wrap real_fn and fake_fn to flatten outputs and capture the output TreeSpec.

    Both wrappers share the same captured output spec: the first call (typically
    fake_fn during tracing) records it, and subsequent calls verify consistency.
    The caller passes in a single-element list and reads captured_out_spec[0]
    after the wrappers have been called.

    Used by both the Dynamo path (_call_leaf_function in torch.py) and the
    make_fx path (_invoke_leaf_function_python in decorators.py).
    """
    ...

def autograd_grad_with_gradient_info(output_infos: Sequence[GradientInfo | None], input_infos: Sequence[GradientInfo | None], grad_outputs: Sequence[Any] | None = ..., retain_graph: bool | None = ..., create_graph: bool = ..., allow_unused: bool = ...) -> tuple[torch.Tensor | None, ...]:
    """
    Compute gradients using GradientInfo, it additionally handles the case
    where input and output infos are None.

    Args:
        output_infos: GradientInfo for each output (None if no grad_fn),
        input_infos: GradientInfo for each input (None if not requires_grad)
        grad_outputs: Gradients w.r.t. outputs

    Returns a tuple of gradients with None for inputs that don't require grad.
    """
    ...

class InvokeLeafFunction(HigherOrderOperator):
    def __init__(self) -> None:
        ...
    
    def __call__(self, real_fn_callable, fake_fn_callable, input_spec, mutated_arg_indices, *flat_args, requires_grad_indices=...): # -> Any:
        """
        real_fn_callable: _LeafCallable wrapping the real function
        fake_fn_callable: _LeafCallable wrapping the fake function
        input_spec: pytree.TreeSpec for unflattening flat_args back to (args, kwargs)
        mutated_arg_indices: comma-separated string of flat-arg indices that are
            declared as mutated (e.g. "1,2"), or "" for no mutations. Encoded as a
            string so it is a pytree leaf for the HOP schema infrastructure.
        requires_grad_indices: comma-separated string of flat-arg indices that
            require grad (e.g. "0,1"), or "" for none.
        """
        ...
    
    def gen_schema(self, real_fn_callable, fake_fn_callable, input_spec, mutated_arg_indices, *flat_args, requires_grad_indices=...): # -> FunctionSchema:
        ...
    


invoke_leaf_function = ...
class InvokeLeafFunctionAutogradOp(torch.autograd.Function):
    @staticmethod
    def forward(ctx, real_fn_callable, fake_fn_callable, input_spec, mutated_arg_indices, *flat_args): # -> Any:
        ...
    
    @staticmethod
    def backward(ctx, *grads): # -> tuple[None, None, None, None, *tuple[Any, ...]]:
        ...
    


@invoke_leaf_function.py_autograd_impl
def invoke_leaf_function_autograd(real_fn_callable, fake_fn_callable, input_spec, mutated_arg_indices, *flat_args, requires_grad_indices=...): # -> Any:
    ...

@invoke_leaf_function.py_functionalize_impl
def invoke_leaf_function_functionalization(ctx, *all_args, **kwargs): # -> Any:
    ...

@invoke_leaf_function.py_impl(ProxyTorchDispatchMode)
def invoke_leaf_function_proxy_mode(proxy_mode, *all_args, **kwargs): # -> Any:
    ...

@register_fake(invoke_leaf_function)
def invoke_leaf_function_fake(real_fn_callable, fake_fn_callable, input_spec, mutated_arg_indices, *flat_args, requires_grad_indices=...):
    ...

@invoke_leaf_function.py_impl(DispatchKey.CompositeExplicitAutograd)
def invoke_leaf_function_dense(real_fn_callable, fake_fn_callable, input_spec, mutated_arg_indices, *flat_args, requires_grad_indices=...):
    ...

