"""
This type stub file was generated by pyright.
"""

import torch
from collections.abc import Callable
from typing import Any
from typing_extensions import ParamSpec, TypeVar
from torch._C import DispatchKey
from torch._higher_order_ops.utils import register_fake
from torch._ops import HigherOrderOperator
from torch.fx import GraphModule
from torch.fx.experimental.proxy_tensor import ProxyTorchDispatchMode
from torch.types import _dtype

_P = ParamSpec("_P")
_R = TypeVar("_R")
log = ...
uid = ...
class Wrap(HigherOrderOperator):
    def __init__(self) -> None:
        ...
    
    def __call__(self, func: Callable[_P, _R], *args: _P.args, **kwargs: _P.kwargs) -> _R:
        ...
    


wrap = ...
class InductorCompiledCode(HigherOrderOperator):
    """
    Defines a HOP for wrapping inductor compiled functions as a callable.
    When used with torch.compile via "wrap_inductor_compiled_regions",
    this HOP will automatically be wrapped and redirect various torch dispatch modes.
    """
    def __init__(self) -> None:
        ...
    
    def __call__(self, func, inputs, *, name: str | None = ...): # -> Any:
        ...
    


inductor_compiled_code = ...
_inductor_compiled_callable_id = ...
class InductorCompiledCallable:
    """
    A wrapper class that holds both the Inductor-compiled callable and the
    original FX graph for fake tensor propagation.
    Each instance gets a globally unique idx at creation (via atomic itertools.count).
    """
    def __init__(self, compiled_callable, original_gm=..., compile_region_name: str | None = ...) -> None:
        ...
    
    def __call__(self, inputs):
        ...
    


class InductorCodeSideTable:
    """
    Side table for storing InductorCompiledCallable objects.

    We cannot put InductorCompiledCallable objects directly into the FX graph
    as graph nodes do not support arbitrary objects. We use this side table
    and pass callable.idx instead.

    Uses WeakValueDictionary so entries are automatically removed when
    the InductorCompiledCallable is no longer referenced elsewhere
    (e.g. after dynamo.reset() drops the compiled code cache).
    """
    def __init__(self) -> None:
        ...
    
    def add_callable(self, callable_obj: InductorCompiledCallable) -> int:
        """Register a callable and return its idx."""
        ...
    
    def get_callable(self, idx: int) -> InductorCompiledCallable:
        """Get the callable at the given index."""
        ...
    
    def __getstate__(self): # -> dict[str, dict[int, InductorCompiledCallable]]:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    
    def reset_table(self) -> None:
        """Reset the table."""
        ...
    


inductor_code_side_table = ...
@inductor_compiled_code.py_impl(DispatchKey.CompositeExplicitAutograd)
def inductor_compiled_code_impl(func, inputs, *, name=...):
    ...

@register_fake(inductor_compiled_code)
def inductor_compiled_code_fake(func, inputs, *, name=...): # -> tuple[Any, ...]:
    ...

@inductor_compiled_code.py_functionalize_impl
def inductor_compiled_code_functionalize(ctx, func, inputs, *, name=...):
    ...

@inductor_compiled_code.py_impl(ProxyTorchDispatchMode)
def inductor_compiled_code_proxy(mode, func, inputs, *, name=...): # -> Any:
    ...

class WrapWithSetGradEnabled(HigherOrderOperator):
    def __init__(self) -> None:
        ...
    
    def __call__(self, enable_grad: bool, wrapped_func: Callable[_P, _R], *args: _P.args, **kwargs: _P.kwargs) -> _R:
        ...
    


wrap_with_set_grad_enabled = ...
class WrapWithAutocast(HigherOrderOperator):
    def __init__(self) -> None:
        ...
    
    def __call__(self, device_type: str, dtype: _dtype | None, enabled: bool, cache_enabled: bool | None, wrapped_func: Callable[_P, _R], *args: _P.args, **kwargs: _P.kwargs) -> _R:
        ...
    


wrap_with_autocast = ...
class DynamoBypassingWrapper(HigherOrderOperator):
    def __init__(self) -> None:
        ...
    
    def __call__(self, wrapper_fn_or_key, inner_fn, *args, **kwargs): # -> Any:
        ...
    


dynamo_bypassing_wrapper = ...
class WrapActivationCheckpoint(HigherOrderOperator):
    """
    This operator is used to wrap torch.utils.checkpoint. This avoids
    TorchDynamo to look into saved tensor hooks and directly passes the control
    to AOT Autograd, which is ok with tracing saved tensor hooks. As a result of
    AOT tracing torch.utils.checkpoint code, we have a backward graph with
    recomputed forward nodes.

    However, we might deprecate this operator soon. The difficulty arises in the
    functionalization of rng ops. Today, there are two different
    functionalization of rng ops - one at AOT autograd and other at Inductor.
    And they are difficult to map to each other. The rng states also complicate
    pattern matching in Inductor. Due to the ease of implementation, we are
    currently inclined towards functionalization at Inductor level, which means
    that duplication/recomputation is done as a compiler pass in the
    partitioners. See TagActivationCheckpoint for more information.
    """
    def __init__(self) -> None:
        ...
    
    def __call__(self, function: GraphModule, *args: Any, **kwargs: Any) -> Any:
        ...
    


wrap_activation_checkpoint = ...
class TagActivationCheckpoint(HigherOrderOperator):
    """
    This operator is supposed to be used only with torch.compile stack. This
    accepts a Fx graph module which needs to be checkpointed. This operator adds
    "recomputable" tag to the nodes of the Fx graph that should be recomputed.

    The goal is to:
    1. Avoid using Dynamo to trace through saved tensor hooks.
    2. For selective checkpointing case, let AOTAutograd trace through
       saved tensor hooks but has special logic with TorchDispatchMode to override
       the usual saved_tensor_hooks fn logic in order to tag the nodes.
    3. Rely on the partitioners to actually duplicate the nodes.
    This sits well in the torch.compile stack, because by the time graph
    reaches partitioner, inductor has already run its functionalization of rng
    ops (by setting fixed seed for each random op, see `replace_random_passes`).
    Therefore, the duplication of nodes, by design, respects the rng states in
    the forward and recomputed forward in backward.
    """
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def divide_kwargs(kwargs): # -> tuple[dict[Any, Any], dict[Any, Any]]:
        """
        checkpoint fn can have mixed kwargs between checkpointed fn and
        checkpoint fn itself. For example
        >> def gn(x, y, z=None):
        >>     a = torch.matmul(x, y)
        >>     if z is not None:
        >>         return torch.matmul(a, z)
        >>     return a
        >> def fn(x, y, z):
        >>     return torch.cos(checkpoint(gn, x, y, use_reentrant=False, z=z))
        In the above case, z belongs to checkpointed function gn, but
        use_reentrant belongs to the checkpoint function. This function splits
        the kwargs into checkpoint_kwargs and gmod_kwargs (or
        checkpointed_fn_kwargs).
        We do sorting to ensure same graph from run to run for better
        debuggability. It is not required for correctness.
        """
        ...
    
    def __call__(self, gmod, *args, **kwargs): # -> Any | None:
        ...
    


tag_activation_checkpoint = ...
def tag_activation_checkpoint_impl(gmod, *args, **kwargs): # -> Any | None:
    ...

@tag_activation_checkpoint.py_impl(ProxyTorchDispatchMode)
def proxy_mode_key(proxy_mode: ProxyTorchDispatchMode, gmod: GraphModule, *args: Any, **kwargs: Any) -> tuple[torch.Tensor]:
    ...

