"""
This type stub file was generated by pyright.
"""

import torch.fx as fx

"""AC rematerialize pass: Duplicates recompute nodes for backward, then DCE removes unused forward versions."""
log = ...
_EMPTY_CUSTOM_META: dict[str, object] = ...
def is_impure_node_for_dce(node: fx.Node) -> bool:
    ...

def remat_using_tags_for_fwd_loss_bwd_graph(gm: fx.GraphModule) -> fx.GraphModule:
    """
    Duplicate recompute nodes for backward use. DCE removes unused forward versions.

    Backward regions are identified by custom["phase"] == "backward" (user
    annotation) or node.meta["autograd_backward"] == True (set automatically when
    Dynamo traces torch.autograd.grad). When the user provides phase
    annotations, only those annotated regions are used.

    Only a single contiguous backward region is supported. If multiple disjoint
    backward regions are detected, an error is raised. Consecutive backward
    operations without non-backward nodes between them are treated as a single
    backward region.
    """
    ...

