"""
This type stub file was generated by pyright.
"""

import torch
from typing import Optional
from torch._C import _cusparselt

__all__ = ["version", "is_available", "get_max_alg_id"]
__cusparselt_version: int | None = ...
__MAX_ALG_ID: int | None = ...
if _cusparselt is not None:
    ...
else:
    ...
def version() -> int | None:
    """Return the version of cuSPARSELt"""
    ...

def is_available() -> bool:
    r"""Return a bool indicating if cuSPARSELt is currently available."""
    ...

def get_max_alg_id() -> int | None:
    ...

