"""
This type stub file was generated by pyright.
"""

import torch

log = ...
_manual_out_variant_registry: dict[torch._ops.OpOverload, torch._ops.OpOverload] = ...
def register_out_variant(functional_op: torch._ops.OpOverload, out_op: torch._ops.OpOverload) -> None:
    """Register a functional op -> out variant mapping."""
    ...

def lookup_manual_out_variant(op: torch._ops.OpOverload) -> torch._ops.OpOverload | None:
    """Return the manually registered out variant for op, or None."""
    ...

def get_out_arg_names(out_op: torch._ops.OpOverload) -> list[str]:
    """Get the names of out arguments for an out variant op."""
    ...

def to_out_variant(op: torch._ops.OpOverload) -> torch._ops.OpOverload | None:
    """
    Given a functional operator overload, return its corresponding out variant.
    """
    ...

def check_out_variant(functional_op: torch._ops.OpOverload, expected_out_op: torch._ops.OpOverload) -> None:
    """
    Checks that to_out_variant returns the expected out variant for a functional op.
    Raises AssertionError if the out variant is not valid.
    """
    ...

