"""
This type stub file was generated by pyright.
"""

import functools
from torch._inductor.utils import clear_on_fresh_cache

log = ...
@clear_on_fresh_cache
@functools.lru_cache(1)
def get_xpu_arch() -> str | None:
    ...

@clear_on_fresh_cache
@functools.lru_cache(1)
def get_xpu_version() -> str | None:
    ...

