"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

"""
Size hinting utilities for symbolic shape expressions.

This module contains the core logic for resolving symbolic expressions to
concrete integer hints. Two strategies are provided:

- _guarding_hint_or_throw_base: strict, only uses backed symbol hints, throws on
  unbacked symbols. Use for correctness-critical guarding decisions.
- _optimization_hint_base: permissive, uses heuristics and fallbacks for unbacked
  symbols. Use for performance optimization decisions.
"""
log = ...
SYMPY_FACTOR_MAX_FREE_SYMBOLS = ...
if TYPE_CHECKING:
    ...
