"""
This type stub file was generated by pyright.
"""

import torch
from dataclasses import dataclass
from typing import Any, ParamSpec, TYPE_CHECKING, TypeVar
from collections.abc import Callable
from torch.fx.experimental.symbolic_shapes import ShapeEnv, TrackedFake

_P = ParamSpec("_P")
_R = TypeVar("_R")
if TYPE_CHECKING:
    ...
log = ...
trace_shape_events_log = ...
__all__ = ["ShapeEnvEvent", "record_shapeenv_event", "replay_shape_env_events", "FakeTensorMeta", "shape_env_check_state_equal", "NotEqualError"]
@dataclass
class ShapeEnvEvent:
    f: Callable[..., Any]
    args: list[object] | None = ...
    kwargs: dict[str, Any] | None = ...
    tracked_fakes: list[TrackedFake] | None = ...
    name: str | None = ...
    def run(self, shape_env: ShapeEnv | None = ...) -> Any:
        ...
    
    def __str__(self) -> str:
        ...
    
    def is_create_fx_call_function(self) -> bool:
        ...
    
    def is_evaluate_expr(self) -> bool:
        ...
    
    def is_defer_runtime_assert(self) -> bool:
        ...
    


NEST = ...
def record_shapeenv_event(*, save_tracked_fakes: bool = ..., name: str | None = ...) -> Callable[[Callable[_P, _R]], Callable[_P, _R]]:
    ...

def replay_shape_env_events(events: list[ShapeEnvEvent]) -> ShapeEnv:
    ...

@dataclass
class FakeTensorMeta:
    tensor_size: tuple[int | torch.SymInt, ...]
    tensor_stride: tuple[int | torch.SymInt, ...]
    tensor_storage_offset: int | torch.SymInt
    is_nested: bool
    def size(self) -> tuple[int | torch.SymInt, ...]:
        ...
    
    def stride(self) -> tuple[int | torch.SymInt, ...]:
        ...
    
    def storage_offset(self) -> int | torch.SymInt:
        ...
    
    def dim(self) -> int:
        ...
    
    @staticmethod
    def from_fake(fake: torch.Tensor) -> FakeTensorMeta:
        ...
    


def shape_env_check_state_equal(env1: ShapeEnv, env2: ShapeEnv, non_state_variable_names: tuple[str, ...], map_value: Callable[[str, object], object]) -> None:
    ...

class NotEqualError(Exception):
    def __init__(self, msg: str, mismatched: list[tuple[str, str, str]]) -> None:
        ...
    


